### ISSUE TITLE
Chart does not play well with tabs from angular-bootstrap

### ISSUE THREAD

**Issue by stanleygu** [n3-charts/line-chart#107]
See [this example](http://plnkr.co/edit/GZBPr3H6M4Kh5ifMmQ27?p=preview).

The top should be the expected thumbnail. In `tab1`, everything looks okay, but then switch to `tab2` and you see that the size is not right.

**Comment by Gregam3** [comment]
Would you consider adding this for pie-chart too? I'm running into the same issue but with pie-chart instead of linechart.
