### ISSUE TITLE
Custom y2 axis labels still clipped in some cases

### ISSUE THREAD

**Issue by marshall007** [n3-charts/line-chart#114]
It appears that if you update the chart data without updating any options, the widths are not recalculated and the y2 labels still get clipped. This behavior occurs on `master`.

Related to #85.

**Comment by chaosmail** [comment]
Hi @marshall007 Is this problem still existing?

**Comment by chaosmail** [comment]
I will close this for now.
However, please let us know if this problem still exists!

**Comment by marshall007** [comment]
@chaosmail sorry for the delay! I haven't noticed this in a while so I assume it's fixed now.
