### ISSUE TITLE
Looks like the tooltipFormatter() option is not working 

### ISSUE THREAD

**Issue by subtubes-io** [n3-charts/line-chart#117]
I was under the impression that there was a `tooltipFormatter()` in the options.

```
$scope.options = {
  axes: {
    x: {
      type: "date",
      tooltipFormatter: function (d) {return moment(d).fromNow();},
      key: "x"
    },
    y: {type: "linear"}
  },
```

It s shown as an option in the [Time Series Example](http://n3-charts.github.io/line-chart/#/examples)

**Comment by satheesh786** [comment]
$scope.renderChart = function () {

            angular.forEach($scope.Bloodglucose, function (bg) {
                bg.measured = new Date(bg.measureddate);
            });
            console.log($scope.Bloodglucose);
            $scope.data = $scope.Bloodglucose;

            $scope.options = {
                lineMode: 'cardinal',
                axes: {
                    x: {
                        type: "date",
                        key: "measured",
                        ticksFormat: "%Y/%m/%d"
                    },
                    y: {
                        type: "linear"
                    }
                },
                series: [
                    {
                        y: "measurement",
                        type: 'area',
                        label: "Blood Glucose",
                        color: "#3498db",
                        dotSize: 3
                    }

                ],

                tooltip: {
                    mode: "scrubber",
                    formatter: function (x, y, series) {
                        return moment(x).format("MMM Do YY") + ': ' + y;
                    }
                } 
       };


        };
