### ISSUE TITLE
Adding Reference in Module makes angular.js stop working

### ISSUE THREAD

**Issue by CaioJahara** [n3-charts/line-chart#128]
Hey there, 

I started implementing angular to my webpage a while ago and I wanna start using n3 to show my charts.
var app = angular.module('medias_ang', ['n3-line-chart']);

Whenever I add the 'n3-line-chart' reference everything I have on my page that uses angular.js stop working.

I use a .ejs file to write my html code and thats how i'm pulling the reference.
<script src="/public/js/line-chart.min.js"></script>

Any idea why it's happening and how I can fix it?

Congrats on N3, it sure looks amazing

**Comment by chaosmail** [comment]
Can we close this issue?

**Comment by sebastien-fragnaud** [comment]
Yup.

**Comment by lorem--ipsum** [comment]
yup
