### ISSUE TITLE
Legend is not capable of displaying arbitrary number of series 

### ISSUE THREAD

**Issue by andrewmtoy** [n3-charts/line-chart#136]
The legend currently does not support an arbitrary number of line series.  If there are many series and/or the width of the chart is very small, some of the series in the legend are not visible because the series information are all placed on the same line.

**Comment by solker** [comment]
It's my realization of this issue.

![chart-small](https://cloud.githubusercontent.com/assets/10127295/6842080/444aece2-d39c-11e4-8929-37a48a876e43.png)
![chart_big](https://cloud.githubusercontent.com/assets/10127295/6842081/44554c78-d39c-11e4-8ac8-6ee35e145d62.png)

**Comment by rfcee** [comment]
+1, this indeed would be very useful

**Comment by BinaryWasteland** [comment]
@lorem--ipsum We could also wrap the legend to be multiple lines aross the bottom and force new line when legend reaches the width of the chart?

**Comment by michalmikolajczyk** [comment]
+1

**Comment by chaosmail** [comment]
This is fixed thanks to HTML legends in v2. Also fully customizable via CSS
