### ISSUE TITLE
add new chart prgramatically

### ISSUE THREAD

**Issue by cscrum** [n3-charts/line-chart#140]
I'm trying to add charts programatically, but I don't know how many charts I will need. My function pulls a different number of data sets which need to be graphed on each call. I've tried just adding a new div with the linechart element with a data array as the argument for data, but all I get is a listing of [object]. How can I add a variable number of charts with different data sets?

**Comment by lorem--ipsum** [comment]
Any update on this ?

**Comment by chaosmail** [comment]
I will close this for now.
However, please let us know if this problem still exists!
