### ISSUE TITLE
"open in playground" visibility suggestion

### ISSUE THREAD

**Issue by melnikovkolya** [n3-charts/line-chart#144]
Hi,

some people may overlook the "open in playground" on the [examples](http://n3-charts.github.io/line-chart/#/examples) page when a mouse hovers over. 

I love the overall design, just thought that it might be beneficial for users to not overlook the possibility of playing with more than a single example that is loaded in the "Playground" page.

PS: not sure if this suggestion should be posted among 'issues'. Please let me know if I should move it somewhere else.

**Comment by chaosmail** [comment]
Check out the new version. It's amazing.
