### ISSUE TITLE
tooltip formatter..

### ISSUE THREAD

**Issue by mittalsumeet** [n3-charts/line-chart#156]
Hi I want to pass tooltip formatter to parse x-axis date and show it in the tooltip. Below is what I am passing as options.

If I am understanding right we need to pass a function to the formatter, how do we do that?

options = {
                lineMode: config.lineMode,
                series: chartSeries,
                stacks: config.stacks,
                axes: config.axes,
                tension: 0.7,
                tooltip: {mode: config.tooltipMode,
                         formatter: function (x, y, series) {
                                         return d3.time.format("%X").parse(x) + ' : ' + y;
                                     }
                        },
                drawLegend: config.drawLegend,
                drawDots: config.drawDots,
                columnsHGap: config.columnsHGap
            }

**Comment by chaosmail** [comment]
Hi @mittalsumeet 
the `formatter` function formats the tooltip in 'scrubber' mode, it should be used like this:

```javascript
formatter: function (x, y, series) {
  return d3.time.format("%X")(x) + ' : ' + d3.format('f.2')(y);
}
```

If you want to style the tooltips in 'axes' mode, please you can use the `tooltipFormat` string.
```javascript
$scope.options = {
  axes: {
    x: {tooltipFormat: '%X'},
    y: {tooltipFormat: 'f.2'}
  }
}
```

I hope this helps!
