### ISSUE TITLE
Grunt task does not build.

### ISSUE THREAD

**Issue by britztopher** [n3-charts/line-chart#158]
I am trying to build the project using the grunt task and it appears that you are missing a dependency somewhere.  I run `npm install`, and when it completes I then run `grunt` and get the following error.  

Running "karma:minified" (karma) task
INFO [karma]: Karma v0.12.24 server started at http://localhost:9876/
INFO [launcher]: Starting browser Firefox
ERROR [launcher]: Cannot start Firefox
        
INFO [launcher]: Trying to start Firefox again (1/2).
ERROR [launcher]: Cannot start Firefox
        
INFO [launcher]: Trying to start Firefox again (2/2).
ERROR [launcher]: Cannot start Firefox

It appears that you need another grunt plugin to get this to run, as I have firefox installed on my mac.  Also, instead of cloning i have forked, but I do not think that is the problem.

**Comment by lorem--ipsum** [comment]
Fixed by #220
