### ISSUE TITLE
Possible/Best way of loading new graph data

### ISSUE THREAD

**Issue by battlecow** [n3-charts/line-chart#162]
I have a multitude of potential graphs with many data points (temperature time series) and would like to be able to dynamically add a new graph without having to pre-load all of the data into the specified format and in the correct order.  Is there a way of accomplishing this task currently or something that might be considered in a future version?

**Comment by battlecow** [comment]
Do you happen to have any ideas for this?  I was still hoping to have this ability in your plugin.

**Comment by lorem--ipsum** [comment]
Well, we have the idea of having an array of arrays as the main data for the chart, would that answer your need ?

**Comment by battlecow** [comment]
I believe it might solve the issue, I can certainly give it a go and see what I can make work.

**Comment by lorem--ipsum** [comment]
Alright, I'll keep you posted on that ! :-)

**Comment by chaosmail** [comment]
Hi @battlecow 
you can take a look on the gitter discussion [https://gitter.im/n3-charts/line-chart](https://gitter.im/n3-charts/line-chart) and give your opinion on the proposed solution :)

**Comment by chaosmail** [comment]
Here is an extensive example of loading, parsing and grouping data: http://plnkr.co/edit/EJ5KXcgz9MTWfSb1muc4?p=preview
