### ISSUE TITLE
NS_ERROR_FAILURE in firefox

### ISSUE THREAD

**Issue by programming-kid** [n3-charts/line-chart#163]
i get very this error when i navigate from parent state to child state (ui-router) only in Firefox

```javascript
".getTextBBox@http://localhost:9000/bower_components/n3-line-chart/dist/line-chart.min.js:6:15149
 .getWidestTickWidth/<@http://localhost:9000/bower_components/n3-line-chart/dist/line-chart.min.js:6:15336
  .getWidestTickWidth@http://localhost:9000/bower_components/n3-line-chart/dist/line-chart.min.js:6:15298
   .adjustMargins@http://localhost:9000/bower_components/n3-line-chart/dist/line-chart.min.js:6:14469
    d/d.update@http://localhost:9000/bower_components/n3-line-chart/dist/line-chart.min.js:6:1431 
    d/d.redraw@http://localhost:9000/bower_components/n3-line-chart/dist/line-chart.min.js:6:927 
    $RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:9000/bower_components/angular/angular.js:13965:22
     $RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:9000/bower_components/angular/angular.js:14227:12 
     timeout/timeoutId<@http://localhost:9000/bower_components/angular/angular.js:15948:24 completeOutstandingRequest@http://localhost:9000/bower_components/angular/angular.js:4877:6 
     Browser/self.defer/timeoutId<@http://localhost:9000/bower_components/angular/angular.js:5250:6 "
``` 
this error is caused even though there is no line chart in child state ,

 even if there is line chart it renders without any error but still i get above error in console 

thanks

**Comment by tatablack** [comment]
Bumping. This seems related to [this ancient Mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=612118), though I'm not sure what can be done about it.

For the record, the error happens [at this line](https://github.com/n3-charts/line-chart/blob/master/src/utils/misc.coffee#L205), and replacing `getBBox` with `getBoundingClientRect` (as suggested in the Mozilla bug thread as a workaround) makes the error go away, though it appears it might have unwanted consequences.

Firefox 35 here.

**Comment by lorem--ipsum** [comment]
Any update on this guys ?

**Comment by francescadamico** [comment]
Same problem here, it has happened after updating to n3-line-chart 1.1.9.
My Firefox version is 38.0. 
Hope this helps

**Comment by chaosmail** [comment]
![bildschirmfoto vom 2015-05-26 17 21 09](https://cloud.githubusercontent.com/assets/2969388/7815939/c300dd76-03cb-11e5-90ca-7f163f3c6ac8.png)

thanks for reporting the issue, I made a screenshot. It seems that in 1.1.9 also the scrubber labels disappeared.
