### ISSUE TITLE
X axis have value added when series is Column

### ISSUE THREAD

**Issue by vitorbvs** [n3-charts/line-chart#169]
I have an example in a JSFiddle that illustrates the issue I will describe: http://jsfiddle.net/c2cvxjx8/1/

I am using the line chart with with a date type X axis. One series is linear, the other is a column.
I have added some functions to parse the Date and to show only the month/year on the axis label.

The problem itself:
Sometimes, depending on the data, the X axis is showing an extra tick, usually on the end.
In my example I have set a toggle data button to show this problem. When the data ends in the 06/214 month, it show a tick with the 07/2014 label with and no data. When I toggle to add one more element in my dataset (the actual 07/2014 data), the last tick shown is the 07/2014.

I have done some debugging on the n3 code, and the n3 directive indeed does insert an element in the beginning and the end of the series, when there is a column series (function adjustXDomainForColumns ). I tried to comment this function. The chart still works, but the columns are shown on the edge of the chart, so I believe the purpose for this function is mainly cosmetic.

I my case this is troublesome because sometimes the extra tick is shown, sometimes not, and to my user this looks like the chart is broken. 
  
Is there any way to prevent this behavior without breaking the chart appearance?

 Thanks

**Comment by chaosmail** [comment]
Hi @vitorbvs 
If not specified, D3.js generates the ticks for the axis very randomly - there is a lot going on under the hood. Best would be to exactly specify which ticks you want to see on the x-axis; you can do this with passing an array of values to the `ticks` option. Please note, that you can also use the `ticksFormat` option to pass a [time formatter string](https://github.com/mbostock/d3/wiki/Time-Formatting) to format the ticks' Date objects properly.
Here is an example that could help you [http://plnkr.co/edit/CTuciu44svWmcOlCoqYP](http://plnkr.co/edit/CTuciu44svWmcOlCoqYP?p=preview)
Please let me know, if this helps to solve your problem.
Best,
Christoph

**Comment by chaosmail** [comment]
Hi @vitorbvs 
I hope your problem is solved, I will close this issue. Let me know if you have still troubles.
Best.
Christoph
