### ISSUE TITLE
graphs in hidden views not sized properl

### ISSUE THREAD

**Issue by cscrum** [n3-charts/line-chart#170]
I have several graphs under different navigation tabs which are loaded with data when the web page loads, but all but the first tab which is visible when the page loads are not sized correctly even if I reload the data when entering the tab. If I resize the window then they appear correctly. How can I force them to size correctly without a resize?

**Comment by rfcee** [comment]
just a follow up query about this. graphs which are initially hidden, now renders in the correct size (initial load), but the legend is "squished", as in the following: 
http://plnkr.co/edit/PRSO0W9UUBGAjbHMpDpH?p=preview

The column graph is initially hidden. Legend renders properly once a series is clicked.
But after doing a window resize, the hidden graph's legend becomes squished again, the graph height is fine, and the width I think is based on the previous width prior to resize.

Does anyone have any workaround for this scenario?
Thanks.
