### ISSUE TITLE
Some bug with v1.1.4 with toggle y axis labels

### ISSUE THREAD

**Issue by brutto** [n3-charts/line-chart#177]
Bowered the last 1.1.4 code realised that if i toggle visibility of series (just clicking on legend mark) y asix dissapeared, and when appear again -- many console errors occure about NaN attribute values, and whole svg holder moved to left in wrong position. 

Test the same code with 1.1.2 (getting from examples) -- it works ok.

**Comment by lorem--ipsum** [comment]
Guys, could you try with the master branch please ? I might have fixed the bug but it would be better if you could confirm it's working for you.

**Comment by anagrius** [comment]
Seeing the same thing on master here.

**Comment by kashban** [comment]
As far as I am concerned I was using the master branch.

**Comment by adressin** [comment]
Same issue here

**Comment by brutto** [comment]
Test v1.1.6 & current master: Y-axis dissapear without errors, but it still dissapeared. =\
Can you make the Y-axis not dissapeaered as in 1.1.2 (probably point me where can i see axis code logic).

PS: btw 1.1.2 have bug with axis positioning with all-zero data points, but 1.1.6 and master seems to be fixed tihis.

PPS: Many thanks for your job and attention!

**Comment by chaosmail** [comment]
Hi @brutto, if everything works fine with v1.1.6, could you close the issue?
thanks a lot :)
