### ISSUE TITLE
tooltips w/ gapped x values break

### ISSUE THREAD

**Issue by franklovecchio** [n3-charts/line-chart#178]
![screen shot 2014-12-19 at 11 37 53 am](https://cloud.githubusercontent.com/assets/341277/5509278/96fa5a74-8773-11e4-9cca-726f6d28c1b5.png)

I can't scroll left in this picture and get the tooltips to show up for the "location:latitude" / "location:longitude" series.

Use-case: timeseries data where the different sensors do not always come in at the same time.

**Comment by lorem--ipsum** [comment]
I think this directive might not be the best tools for the amount of data you have...

**Comment by chaosmail** [comment]
Hi @franklovecchio 
The scrubber tooltip always looks for the nearest x value of every series according to the mouse position. Have you tried using the tooltips in 'axes' mode, this might be better for you? You could display just the x:y values (like "10min : -104.9") there and use the `on-focus` event (or `on-hover` for 'axes' mode) to display the full-size tooltip next to the chart.

**Comment by alexvanstalkeR** [comment]
Same issue to me:
http://codepen.io/anon/pen/LVgygP (second point)
I can't afford adding extra (interpolated) points just to let tooltips display normally.

**Comment by lorem--ipsum** [comment]
Closing this as related to v1.
