### ISSUE TITLE
Any way of setting the axis color ?

### ISSUE THREAD

**Issue by awdng** [n3-charts/line-chart#182]
I might just not see it in the docs, but is there a way to set the axis color to something else than black ? I have a page with a rather dark background, so the axis being black makes them almost invisible. I briefly looked through the code but did not find a place where that color is set, otherwise i could make a pull request. Great work on the directive though!

**Comment by sebastien-fragnaud** [comment]
Hey, thanks for the interest !
Have you tried CSS ?
