### ISSUE TITLE
Hiding series doesn't redraw stacked bar chart

### ISSUE THREAD

**Issue by roxeteer** [n3-charts/line-chart#183]
Based on the example chart you have on your site, line-chart doesn't properly redraw the chart when you hide a series in a stacked bar chart. You can test it at http://bit.ly/1xYlUHy

If you hide a series that is between other series in the stack, the series above it keep hanging in the air. I would've assumed that after hiding a series there were no empty gaps and the Y-axis was re-scaled to match the visible data.

Here's a screenshot:

![screen shot 2015-01-09 at 16 36 37](https://cloud.githubusercontent.com/assets/477255/5681090/d56d61c4-981d-11e4-9f94-2cae80b3a527.png)

**Comment by valentinvieriu** [comment]
+1
