### ISSUE TITLE
tooltip on Ionic

### ISSUE THREAD

**Issue by Konkko** [n3-charts/line-chart#186]
Hi, 

I'm building an app using Ionic framework and the tooltip doesnt seem to work when run the app from android. The examples work on the phone browser but on the app it doesnt... any hints?

**Comment by Konkko** [comment]
Solved

**Comment by eplicanic** [comment]
Any pointers on how you resolved this?

**Comment by Konkko** [comment]
Changed the event type

if (event.target.classList[0] === 'glass') {
            var touches = event.changedTouches,
                first = touches[0],
                type = "";
            switch (event.type) {
                case "touchstart": type = "mouseover";break;
                case "touchend": type = "mousemove";break;
                default: return;
            }

            var simulatedEvent = document.createEvent("MouseEvent");
            simulatedEvent.initMouseEvent(type, true, true, window, 1,
                                      first.screenX, first.screenY,
                                      first.clientX, first.clientY, false,
                                      false, false, false, 0/*left*/, null);

            first.target.dispatchEvent(simulatedEvent);
            event.preventDefault();
        }
