### ISSUE TITLE
x-axis date type extra day/hour when dealing with exact dates

### ISSUE THREAD

**Issue by bloodhawk** [n3-charts/line-chart#189]
Here is an example of the code and data I am using:

```
$scope.data = [
    {
      x: new Date(2015, 0, 1, 1),
      data: 50,
      data2: 100
    },
    {
      x: new Date(2015, 0, 1, 2),
      data: 100,
      data2: 100
    },
    {
      x: new Date(2015, 0, 1, 3),
      data: 45,
      data2: 3
    },
    {
      x: new Date(2015, 0, 1, 4),
      data: 5,
      data2: 10
    },
    {
      x: new Date(2015, 0, 1, 5),
      data: 200,
      data2: 20
    },
    {
      x: new Date(2015, 0, 1, 6),
      data: 50,
      data2: 100
    },
    {
      x: new Date(2015, 0, 1, 7),
      data: 2,
      data2: 200
    },
    {
      x: new Date(2015, 0, 1, 8),
      data: 76,
      data2: 42
    },
    {
      x: new Date(2015, 0, 1, 9),
      data: 13,
      data2: 100
    },
    {
      x: new Date(2015, 0, 1, 10),
      data: 10,
      data2: 10
    }
  ];
  $scope.options = {
    stacks: [{axis: 'y', series: ['id_1', 'id_2'] }],
    lineMode: 'linear',
    series: [
      {
        id: 'id_1',
        y: 'data',
        label: 'data',
        type: 'column',
        axis: 'y'
      },
      {
        id: 'id_2',
        y: 'data2',
        label: 'data2',
        type: 'column',
        axis: 'y'
      }
    ],
    axes: {
      x: {
        key: 'x',
        type: 'date',
        labelFunction: function(value) {
          //takes the date object? and returns a string
          return (value.getMonth() + 1) + '/' + value.getDate();
        }
      },
      y: { type: 'linear' }
    },
    tension: 0.7,
    tooltip: {
      mode: 'scrubber',
      formatter: function(x, y, series) {
        return series.y + ' ' + (x.getMonth() + 1) + '/' + x.getDate() + ' ' + y;
      }
    },
    drawLegend: true
  };
```
  
  Or the data may look like this: 
  
  ```
  $scope.data = [
    {
      x: new Date(2015, 0, 1),
      data: 50,
      data2: 100
    },
    {
      x: new Date(2015, 0, 2),
      data: 100,
      data2: 100
    },
    {
      x: new Date(2015, 0, 3),
      data: 45,
      data2: 3
    },
    {
      x: new Date(2015, 0, 4),
      data: 5,
      data2: 10
    },
    {
      x: new Date(2015, 0, 5),
      data: 200,
      data2: 20
    },
    {
      x: new Date(2015, 0, 6),
      data: 50,
      data2: 100
    },
    {
      x: new Date(2015, 0, 7),
      data: 2,
      data2: 200
    },
    {
      x: new Date(2015, 0, 8),
      data: 76,
      data2: 42
    },
    {
      x: new Date(2015, 0, 9),
      data: 13,
      data2: 100
    },
    {
      x: new Date(2015, 0, 10),
      data: 10,
      data2: 10
    }
  ];
  ```

When I provide this data to n3 linecharts I get start and end dates on the x-axis that are always 1 hour/day ahead and before. Is there a way of telling n3 linecharts to start on the exact date rather than an average step calculated by:
  
  ```
  getAverageStep: function(data, field) {
        var i, n, sum;
        if (!(data.length > 1)) {
          return 0;
        }
        sum = 0;
        n = data.length - 1;
        i = 0;
        while (i < n) {
          sum += data[i + 1][field] - data[i][field];
          i++;
        }
        return sum / n;
      }
 ```

Dividing the returned result of getAverageStep by 2 and returning it seems to give the chart the behavior I'm wanting when it's passed to createAxes and x is set to the value returned by d3.time.scale().rangeRound([0, width]);

I also tried giving it a min and max function for the dates, but I'm  still getting the same behavior.

**Comment by lorem--ipsum** [comment]
Hi ! Thanks for the interest. The chart adds an extra abscissa at each end of the x-axis if you want column series. This is a way to prevent any column from overlapping with the vertical axes. On a side note, the dates in your data are not correct. Read more about the Date constructor here : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

I strongly advise you to deal with dates either as an ISO string, or as timestamps. :-)

**Comment by bloodhawk** [comment]
My interest was the ability to not add an extra abscissa at each end and still maintain the columns from causing issues with the y-axes.

**Comment by lorem--ipsum** [comment]
Then compute the ticks from your data : http://plnkr.co/edit/isjthqZ1B9Cz9zx4hEwv?p=preview

**Comment by nishadotcom** [comment]
How to set X axis period????

Ex:

 ----------------------------------------------------------------------------------------------------
0                  3                 6               9             12              15           18           21

Instead 

-----------------------------------------------------------------------------------------------------------
0              5                 10                  15                     20                     25                 30

Here, the period is 5.

How to do it????
