### ISSUE TITLE
Getting weird line showing on basic chart

### ISSUE THREAD

**Issue by andylockran** [n3-charts/line-chart#193]
http://uth.zrmt.com/angular/#/today

The weirdness is that the line is set to area, two data series work ok, but one data series is showing some random line, and I can't get rid of it:

   $scope.data = ElectricityUsage.today();

    $scope.options = {
    	axes: {
    		x: {key: 'id', type: 'linear'},
    		y: {type: 'linear',	max: 13000},
    		y2: {type: 'linear', min: 0, max: 200, ticks: 5}
    	},
    	series: [
    		{ y: 'ch01', label: 'Control4',  color: 'red', type: 'area', axis: 'y2'},
    	 	{ y: 'ch02', label: 'Study', color: 'green', type: 'area', axis: 'y2'},
    		{ y: 'chh',  label: 'Total', color: 'blue', type: 'area', axis: 'y'}
    		]
    	}	
  });

data can be seen at http://uth.zrmt.com/api/index.php/today if you want to check the source data.

**Comment by andylockran** [comment]
Hey guys,

Sorry - to clarify I'm pretty new to javascript and if you can give me some guidance on how to go about troubleshooting issues like this, that would be awesome - thanks for the top work so far.

Andy

**Comment by lorem--ipsum** [comment]
Hey, thanks for the interest. The problem was : you didn't hide the dots. Her's a working sample based on your data and options : http://plnkr.co/edit/c7BQwahZlnmqhU0ATs94?p=preview

lorem--ipsum

**Comment by andylockran** [comment]
Thanks for the response; much appreciated.  Is it possible to hide the line
at all for the Total count?  It's still showing, when I'd like it to just
show area.

**Comment by lorem--ipsum** [comment]
Okay, there's something else I forgot to check. There are weird lines because your data is poorly formatted. Here's a better way to do that: http://plnkr.co/edit/6NNazuXY6TiU7dLXWfsJ?p=preview

About the lines, it's currently not possible using purely the options to hide them. You can still hide them using CSS, though.
