### ISSUE TITLE
Ability to draw horizontal grid lines?

### ISSUE THREAD

**Issue by studiobrain** [n3-charts/line-chart#195]
Not an issue as much as a request: I have been looking without resolve for a way to add horizontal grid lines or possibly extend the exiting ticks to be the width of the graph.  Is this possible and if so can you direct me to the line number I might update that ability?

**Comment by Avien** [comment]
+1
I need that feature as well

**Comment by lorem--ipsum** [comment]
I think you can just add a series with two data points as a workaround... But you'll have a tooltip on it, then. What about this syntax in the options : 

```js
{
  extra: {
    hLines: [{axis: 'y', color: 'red', value: 12}]
  }
}
```

?
