### ISSUE TITLE
Chart transition/duration/... ?

### ISSUE THREAD

**Issue by am74po** [n3-charts/line-chart#197]
Hi.

The chart is re-drawn each data binding, right?
Is there any way to animate this?

I get new data each 2 seconds - and add it to the previous data.
 Can this change, from state A to state B take duration of 2 seconds?

Any help will be great.

**Comment by lorem--ipsum** [comment]
Hi, unfortunately the chart hasn't really been designed for this use case (updated data)... So the answer would be no at the current moment...
