### ISSUE TITLE
Drill actions

### ISSUE THREAD

**Issue by dorlandode** [n3-charts/line-chart#199]
Is there a way to do drill actions on individual data points?  For example, on a bar or on a point on a line chart?

**Comment by nesler** [comment]
Is this meant as the ability to hook events on data points? If so, huge :+1: from me!

**Comment by lorem--ipsum** [comment]
Hmmmm I think that's not implemented right now, but that would probably be easy to do... PR anyone (don't forget the tests :-) ?

**Comment by lorem--ipsum** [comment]
Fixed by #221
