### ISSUE TITLE
Error: Invalid negative value for <rect> attribute height="-79"

### ISSUE THREAD

**Issue by Knudian** [n3-charts/line-chart#201]
Hello,

D3 is throwing me that error twice on my page.
Those are the reference to n3-line-charts : 
createGlass on n3-chart.line.js:89
scope.update on n3-chart.line.js:39

I am using those elements :
- AngularJS 1.40-beta-5
- AngularUI 0.12
- jQuery 2.13
- D3.v3

Note :
- All the source code used in my page, for that line chart, is copy/pasted from the github homepage.

Edit :
Here is the result of the computed graph in my page
```html
<div class="col-md-6">
    <div data="datas" options="options" class="ng-isolate-scope chart" style="font-size: 0px;">
        <svg width="370" height="1">...</svg>
    </div>
</div>
```
Just the ' height="1" ' is surprising me.

**Comment by lorem--ipsum** [comment]
Yeah, you should try giving an explicit height to your chart element (see Readme on project's github page).
