### ISSUE TITLE
y Axis title / label are not positionned properly on first load

### ISSUE THREAD

**Issue by HadrienPierart** [n3-charts/line-chart#202]
When I load my graph for the first time, here is what is displayed : 
![screenshot from 2015-03-14 17 08 14](https://cloud.githubusercontent.com/assets/738871/6652389/f9e6cf0a-ca6c-11e4-94e2-11ab119ce1cd.png)

And the if I click one of the titles to hide the serie and click again, the titles get spaces properly like that : 
![screenshot from 2015-03-14 17 08 27](https://cloud.githubusercontent.com/assets/738871/6652391/1375ec30-ca6d-11e4-942e-112f71c55a8b.png)

Any idea where this could come from.
Here is the conf of my graph : 

    {
      drawLegend: true,
      drawDots: true,
      stacks: [],
      axes: {
        x: { key: 'x', labelFunction: function(value) { return moment(value*1000).format('DD-MM-YYYY'); },
          type: 'linear', min: dataTot.xMin, max: dataTot.xMax, ticks: nbTicks},
        y: { type: 'linear', min: dataTot.yMin, max: dataTot.yMax, ticks: nbTicks}
      },
      series: [
        { y: 'y',  color: '#88BF57', thickness: '2px', type: 'line', dotSize: 3, label: 'Total' },
        { y: 'y2', color: '#414E92', thickness: '2px', type: 'line', dotSize: 3, label: 'Men' },
        { y: 'y3', color: '#EC7161', thickness: '2px', type: 'line', dotSize: 3, label: 'Women' }
      ],
      lineMode: 'monotone',
      tension: 0.7,
      tooltip: { mode: 'scrubber', formatter: function(x, y) { return moment(x * 1000).format('DD-MM-YYYY') + ' : ' + y; }},
      columnsHGap: 5
    }
    
Thanks a lot for the work by the way, very handy to create nice charts !

**Comment by mpenza** [comment]
Been trying to track down a solution to this same issue. I've determined the cause. In the drawLegend() function, computeLegendLayout is called before the text is actually rendered and as a result getBBox() returns a 0 sized rectangle. Not sure the best way to fix this. Ideally, the layout of the legend should be calculated after the test is rendered, but I'm not sure if that's possible to detect.  I may hack it and just update the layout after a brief delay.

**Comment by mpenza** [comment]
Okay, came up with a fix.  Not sure its the best, but it works.

The issue occurs because when Angular calls the link function, the element is not yet attached to the DOM.  Therefore, the SVG isn't rendered. But we can delay the drawing of the legend to the next digest cycle with a $timeout call.  If the scope.update() function, just wrap the _u.drawLegend in a $timeout call.

```coffeescript
if options.drawLegend
  $timeout( 
    () -> 
      _u.drawLegend(svg, options.series, dimensions, handlers)
      return
    0)
```
