### ISSUE TITLE
Is it possible the chart to be 100% of the width of the parent?

### ISSUE THREAD

**Issue by hristod** [n3-charts/line-chart#204]
It seems there is 50px padding on the left and right of the chart when I create it. Is there an option to remove the padding?

**Comment by chaosmail** [comment]
Hi @hristod,
with the 1.1.8 release you can customize the margins of a chart. Here is a demo showing this: [http://plnkr.co/edit/pfQAav4ty8cgJ5Ohica5](http://plnkr.co/edit/pfQAav4ty8cgJ5Ohica5?p=preview)
However, removing the margins also removes the y-axis caption, not sure if you want this. Let me know if this solves the problem for you!
Best,
Christoph
