### ISSUE TITLE
Options for legend layout & style

### ISSUE THREAD

**Issue by eddywashere** [n3-charts/line-chart#206]
Would this project be open to legend changes that would add options to render the legend as a square or text label instead of just the circle w/ line type icon? See examples below:

![legends](https://cloud.githubusercontent.com/assets/399776/6887508/59aa470a-d616-11e4-9860-370bc1a99946.png)

I could potentially use the `<rect>` svg element and just the `<text>` element to implement these changes.

**Comment by lorem--ipsum** [comment]
Sure, great idea !
