### ISSUE TITLE
Can't see tooltip text when the series color is white.

### ISSUE THREAD

**Issue by willynilly** [n3-charts/line-chart#207]
The tooltip text color is fixed to be white, so it cannot be seen if the series color is white.  We need a setting specify the tool tip text color.

**Comment by lorem--ipsum** [comment]
Wait, if your series is white, how can you see it ? Do you have a dark background ?

Could you provide an example of the problem please ? Thanks :-)

**Comment by MattiSG** [comment]
You can fix this by styling the `text` within your container with `! important`. [Example](https://github.com/sgmap/mes-aides-ui/commit/394e520fe036f39ad3345d5cb96f3e6c2ab0786a#diff-dd500cf71219ed0095e3033569864083R2).

**Comment by lorem--ipsum** [comment]
Closing this as no longer happening in v2.
