### ISSUE TITLE
getBBox exception on switching tooltip mode "NONE"

### ISSUE THREAD

**Issue by shashank181291** [n3-charts/line-chart#208]
while configuring the options to render the graph, if we opt to switch the tooltip mode "none", an exception is thrown while hovering over the svg elements of the graph, it is: 
Uncaught TypeError: Cannot read property 'getBBox' of null

Look forward to its resolution in further versions.
![n3-issue](https://cloud.githubusercontent.com/assets/11733174/6914222/f70e57a8-d7a5-11e4-8e5f-0a36bf98af1a.png)

**Comment by shashank181291** [comment]
this patch worked for me:

--- app/components/n3-line-chart/build/line-chart.js	2015-04-06 12:55:43.934282930 +0530
+++ app/components/n3-line-chart/build/line-chart.js	2015-04-06 12:47:36.026275020 +0530
@@ -845,7 +845,7 @@
         return bbox;
       },
       getTextBBox: function(svgTextElement) {
-        return svgTextElement.getBBox();
+        return svgTextElement != null ? svgTextElement.getBBox() : {};
       },
       getWidestTickWidth: function(svg, axisKey) {
         var bbox, max, ticks, _ref;

**Comment by shashank181291** [comment]
this patch worked for me:

--- app/components/n3-line-chart/build/line-chart.js	2015-04-06 12:55:43.934282930 +0530
+++ app/components/n3-line-chart/build/line-chart.js	2015-04-06 12:47:36.026275020 +0530
@@ -845,7 +845,7 @@
         return bbox;
       },
       getTextBBox: function(svgTextElement) {
--        return svgTextElement.getBBox();
++        return svgTextElement != null ? svgTextElement.getBBox() : {};
       },
       getWidestTickWidth: function(svg, axisKey) {
         var bbox, max, ticks, _ref;

**Comment by lorem--ipsum** [comment]
Please submit a PR with this patch :-)

**Comment by lorem--ipsum** [comment]
This has been solved (at least in 1.1.10, maybe before). Closing it !
