### ISSUE TITLE
Date interpolation and labelFunction

### ISSUE THREAD

**Issue by mgohin** [n3-charts/line-chart#213]
Hi,

I'm using dates between 8 and 17 every day but the lib interpolate hours between (from 17:01 to 7:59) and I don't want to.

So I tried to use 'linear' type and put values from 0 to my max for the x axis, but now in labelFunction I can't have the x value, I got values like 0.2.

Is it possible to disable date interpolation like first suggested in #97, or to have the x value I did put in data for labelFunction ?

I'm using on x axis ticks=5

I wouldn't like to change lib because of a simple labelFormatting problem ;)

**Comment by mgohin** [comment]
I just found a workaround but not very nice

    labelFunction: function(v){
              if(v === parseInt(v)){
                //I got get my data in my array with v as index and return my date formatted
              }
              return '';
            }

Could be nice to disable date interpolate to let us use our date objects

**Comment by chaosmail** [comment]
Hi @mgohin 
The ticks method in d3 does a lot of things under the hood - often also a lot of interpolations and adjustings. However, I can also handle an array of values instead a number of ticks. Have you tried to put the array of dates directly to the ticks option?

```javaschript
// Your data
$scope.data = [
  {x: new Date(), y:20, ...},
  {x: new Date(), y:40, ...}
];

// Generate an array with your ticks
$scope.ticks = $scope.data.map(function(d){
  return d.x;
})

$scope.options = {
  axes: {
    x : {
      type:'date', ticks: $scope.ticks
    }
  }
}
```

Let me know if this helps! Btw. the latest version supports the `ticksFormat` option, where you solely  define a format string which is passed to d3 internally (d3.format or d3.time.format for type 'date').

Best,
Christoph

**Comment by chaosmail** [comment]
I hope your problem is solved, I will close this issue.
Best,
Christoph
