### ISSUE TITLE
Rotation of x axis labels

### ISSUE THREAD

**Issue by henhal** [n3-charts/line-chart#214]
I have a column chart where each column's label on the x axis is a string, and each label must be visible. When having fairly large series, this means the labels will overlap. 

I've been fiddling around with having the labels rotated 45 or even 90 degrees with the help of [http://www.d3noob.org/2013/01/how-to-rotate-text-labels-for-x-axis-of.html](this blog), but I haven't got it looking that great, and besides it would be awesome if this could be provided by the library using some option on the axis such as 

    axes: {
        x: {
            key: 'x',
            type: 'linear',
            rotate: 45,
            ...
    }

The label would then have to align either the beginning or the end of the text to the corresponding point on the x axis depending on if the angle is positive or negative.

Any thoughts on this?

**Comment by lorem--ipsum** [comment]
I don't really have enough time to work on this right now, but I like the idea !
