### ISSUE TITLE
Fixed column width

### ISSUE THREAD

**Issue by henhal** [n3-charts/line-chart#215]
I've spent quite some time trying to figure out if it's possible to set a fixed width on columns in a column chart. I have a situation where sometimes my chart will consist of only 1-3 data points, and then the columns will expand to become extremely wide. Is there an option I've missed which makes it possible to set a fixed and/or max width on each column bar?

I've tried using min and max on my x axis to make sure I get let's say a range of 0-20 even if only having a data set with values for x = 0 and x = 1, but that just makes my x = 0 column appear to the left of the y axis and/or disappear, it doesn't seem to affect the width?

**Comment by cangoektas** [comment]
Can anyone suggest a solution for 1.x? I'll need to set the column width and was wondering where to begin and what would be the most elegant way to do it. Any help is appreciated.

**Comment by chaosmail** [comment]
Hi @cangoektas 
is there a specific reason why you want to set a fixed with for the bars in a bar chart? Are they currently too small, too big or do you have other displaying issues?
Best,
Christoph

**Comment by cangoektas** [comment]
Hi @chaosmail 
thanks for the quick reply! The reason is only that I need to implement a given design. The design specifies a fixed column width and a dynamic space between them. Any ideas on how to tackle this problem?

Thanks a lot!

**Comment by chaosmail** [comment]
ok, that's sounds exactly like the moment when you would need fixed column widths :smile: 
alright, we don't have this options in the current version, but it would be rather easy to fork/implement this. What do you think, wanna try it? Of course i would guide you ;)

**Comment by cangoektas** [comment]
Yeah sure, I could try that. Thanks for offering your help I'll definitely need it. :) Just don't have any experience with CoffeeScript yet so it'll take me a bit longer I guess.

Should we move the conversation somewhere else?

**Comment by chaosmail** [comment]
yeah, let's move over there https://gitter.im/n3-charts/line-chart/fixed-column-width

**Comment by lorem--ipsum** [comment]
Hey, we're closing this because it's been a while and we're trying to avoid zombie issues. If the problem persists, please open a new issue (and don't forget, your issue is much more likely to be fixed if you provide a working [CodePen](http://n3-charts.github.io/line-chart/#/examples) : easier for us, faster for you !).

Thanks again for helping us making n3-charts awesome.

--
_Sébastien & Christoph_
