### ISSUE TITLE
Tooltip: Is it possible to show the tooltip on each series separately and not all of them together?

### ISSUE THREAD

**Issue by Avien** [n3-charts/line-chart#216]
And only when I mouse over a specific series to get it's coordinates?
(not by using the axes mode)

**Comment by lorem--ipsum** [comment]
Hmmmm like this : http://codepen.io/lorem--ipsum/pen/LVxwmV ?

**Comment by Avien** [comment]
Nope,
Something like this (multiple Y axes)
![image](https://cloud.githubusercontent.com/assets/4569044/7934987/4f2670a4-0935-11e5-812d-1fb3adee8de1.png)

**Comment by lorem--ipsum** [comment]
There is not tooltip on your example ?

**Comment by lorem--ipsum** [comment]
Any update on this ?

**Comment by Avien** [comment]
No thanks

**Comment by lorem--ipsum** [comment]
Alright, closing it then :-)
