### ISSUE TITLE
Wrong number rendering on yAxis

### ISSUE THREAD

**Issue by bkolada** [n3-charts/line-chart#223]
Hi, 
Great job with that lib but I found some glitch with rendering numbers on yAxis, here is plunker that shows that problem [http://plnkr.co/edit/zwTeO1HOwqri4f2hgNrg?p=preview](http://plnkr.co/edit/zwTeO1HOwqri4f2hgNrg?p=preview). (edit) Problem shows when you are setting number greater equal then 100000

Problem detected on google-chrome 42.0.2311.135 and firefox 37.0.2.

Is it possible to solve that or do you have some quick workaround?

Br,
Bart

**Comment by chaosmail** [comment]
Hi,
you could use a labelFunction to format the axis values, e.g. to scientific format 1e6. 

```js
// Define a formatter function
var formatter = d3.format('e');

$scope.options = {
  ...
  axes: {
    y: {
      labelFunction: formatter
    }
  }
}
```

Here is a demo [http://plnkr.co/edit/QL0gNTZzlfLOiXk8hgIx](http://plnkr.co/edit/QL0gNTZzlfLOiXk8hgIx?p=preview)

Best,
Christoph

**Comment by bkolada** [comment]
Christoph, 
thanks a lot for that snippet, nice simple solution that I was looking for.

Br,
Bart
