### ISSUE TITLE
Does the "on-click" work for line charts?

### ISSUE THREAD

**Issue by vlamic** [n3-charts/line-chart#242]
Hi,

First of all, thank you for such a great library. I totally love it!

I'm trying to figure out how to handle clicks. I couldn't make it work for some reason. Could you look at example and see what am I doing wrong? You can find in there: http://codepen.io/anon/pen/mJRPyX

The top chart is implemented having "on-click" method and the bottom chart has a standard angularjs "ng-click". The standard angularjs "ng-click" works (you will see the output in console), but the "on-click" is not being handled.

Thank you!

**Comment by chaosmail** [comment]
Hi @vlamic 
Unfortunately, the scrubber tooltip generates an overlay and therefore the click events are not propagated properly. For the moment, the events `click` and `hover` just work with the tooltip mode 'axes'.

If you add `tooltip: {mode: 'axes'},` to your options, the click event should be triggered properly.

Best,
Christoph

**Comment by vlamic** [comment]
Thanks Christoph!

**Comment by chaosmail** [comment]
I hope this could solve your problem @vlamic 
let me know if you need any more help
