### ISSUE TITLE
line chart 

### ISSUE THREAD

**Issue by udaykanth3** [n3-charts/line-chart#249]
i want to display the point on the graph with out using tooltips="true"  ..any possible plzz reply me

**Comment by chaosmail** [comment]
Hi @udaykanth3 
do you mean without enabling tooltips? you could use `tooltip: {mode='none'}` to achieve this.
Hope this answers your question.
Best,
Christoph

**Comment by udaykanth3** [comment]
NO,automatically i wnt to display the point on the graph itself ...like (3,5) on the graph

**Comment by udaykanth3** [comment]
thanks for reply ...my question is i wnt to display the (x,y) values on the
graph only...so plz reply me

**Comment by chaosmail** [comment]
You need a little hack to achieve this. Please take a look at this example: [http://codepen.io/anon/pen/PqWxbM](http://codepen.io/anon/pen/PqWxbM)
