### ISSUE TITLE
Redraw line chart

### ISSUE THREAD

**Issue by neilgilbert1234** [n3-charts/line-chart#25]
Apologies i am relatively new to Angularjs.
I can't seem to get the chart to redraw the data when using the http service. I am simply updating the $scope.data (this is being used as the data for the chart) but it doesn't seem to update the chart?

I am calling the service from a button, this calls the following :
    $scope.searchMonthlyTransactions = function () {
        $http.get('http://sas-laptop9/CashFlowService/Service1.svc/MovementTransactions/).success(function (data) {
            $scope.data = data.MovementTransactionsResult;
        });
    }

Am i doing something stupid? Or should it update the chart with my data?
I know the data returned is ok, as if i call it "on load" the graph plots ok.

Any help would be great

**Comment by kasimmo** [comment]
Has anyone figured this one out yet? I've updated $scope.data followed with $scope.$apply() to no avail. The chart does not change until I click on the legend... then it updates.

**Comment by chaosmail** [comment]
Hi @andrewfosterrth 
do you have a pluker demo to illustrate your problem (you can start modifying [this one](http://plnkr.co/edit/hsyGJWt0gixLUCsjEdmN?p=preview))? This would be very helpful to find the bug.
Best,
Christoph
