### ISSUE TITLE
RTL support for line chart

### ISSUE THREAD

**Issue by HarelM** [n3-charts/line-chart#254]
Hi,
First and foremost, great project.
I'm writing a site in an rtl language, when setting the dir=rtl on the html the text on both the graph labels and the tool tip is not presented correctly.
I currently have a workaround that I place dir=ltr on the div that hold the line-chart.
Can you please take a look?

**Comment by chaosmail** [comment]
Hi @HarelM 
could you please provide a plunkr to illustrate this problem? You can just fork and modify this one: [http://plnkr.co/edit/wu3xkGn28RPrhkcelYKo?p=preview](http://plnkr.co/edit/wu3xkGn28RPrhkcelYKo?p=preview)
Best,
Christoph

**Comment by HarelM** [comment]
Wow, that was a fest response!
see below, thanks.
http://plnkr.co/edit/vLHf2vjjG7fBe1bmQ1B0?p=preview

**Comment by chaosmail** [comment]
Thanks for the plunkr, it really helps to understand your problem. We will have a look at this and keep you updated!

**Comment by HarelM** [comment]
Great, If you have any questions on how the rtl graph should be presented, please feel free to use this thread. In general, for rtl, I would expect that the entire control would be "mirror" along the y axis - i.e. if there is a picture and text so that the picture is left to the text in ltr version I would expect the picture to be right to the text in rtl.
Again, Thanks.

**Comment by chaosmail** [comment]
Hi @HarelM 

I just submitted a PR to support RTL. Here is a demo where you can already play around [http://plnkr.co/edit/Zgj449UNxnGJ7rGAF2xW](http://plnkr.co/edit/Zgj449UNxnGJ7rGAF2xW?p=preview)

Please let me know, if you have any problems or issues.

Best,
Christoph

**Comment by HarelM** [comment]
Hi @chaosmail 
Thanks for the update - I'm a bit puzzled...
If I look at your new plunker the dir="rtl" exists and the graph looks good (although not really rtl - I'll explain at the bottom).
but when I remove the dir="rtl" the graph goes back to looking bad.
I have a site that I translate from ltr to trl languages so I need both of them working correct when changing this attribute.
basically, since rtl language uses the same method to present graphs the only change that need to be done is to keep the graph looking the same and replace the position of the circles in the legend:
i.e.:
```
______________________
() value     () value2
```
should be:
```
______________________
value2 ()     value ()
```

Thanks again for all the hard work! keep it up!
Harel M.

**Comment by chaosmail** [comment]
Hi @HarelM 
ok, so basically I changed everything (scrubber labels text, rendering of legend text and axis text) but the position of the circle; hence the confusion. I didn't want to autodetect if there is a `dir="rtl"` attribute on a parent element, that's why you have to set an additional option.
Swapping the circles of the legend to the other side is no problem :D

**Comment by chaosmail** [comment]
I modified the setup, to contain one RTL and one normal, chart [http://plnkr.co/edit/Zgj449UNxnGJ7rGAF2xW?p=preview](http://plnkr.co/edit/Zgj449UNxnGJ7rGAF2xW?p=preview)
Is this similar to your setup?

**Comment by HarelM** [comment]
Looks good, what happens if I want to change the directions on run time - would changing the rtl field in the options on run time will affect the chart?
I'm sorry for being picky, I hope you'll forgive me. :-)

**Comment by chaosmail** [comment]
that's the beauty of data-binding, the chart will redraw automatically when you toggle the rts option. However, you need to also toggle the `dir="rts"` attribute on the parent element

**Comment by chaosmail** [comment]
but actually you could also set the `dir="rts"` attribute with angular ;)

**Comment by HarelM** [comment]
Great! I'm doing it anyway using ```dir="{{my_dir_variable}}"``` on the html tag.

**Comment by chaosmail** [comment]
thats awesome, well than you could just add sth like this to the line-chart options
```javascript
$scope.options = {
  rtl: $scope.my_dir_variable == 'rtl' ? true : false
}
```

**Comment by HarelM** [comment]
It's a bit more complicated, but the point is well taken. Thanks a lot for all the hard work!

**Comment by lorem--ipsum** [comment]
Hey, we're closing this because it's been a while and we're trying to avoid zombie issues. If the problem persists, please open a new issue (and don't forget, your issue is much more likely to be fixed if you provide a working [CodePen](http://n3-charts.github.io/line-chart/#/examples) : easier for us, faster for you !).

Thanks again for helping us making n3-charts awesome.

--
_Sébastien & Christoph_
