### ISSUE TITLE
Prevent column overlaping

### ISSUE THREAD

**Issue by jpagand** [n3-charts/line-chart#255]
How to prevent column overlapping like that?

![54sdg5ds6](https://cloud.githubusercontent.com/assets/2401332/8083776/63074528-0f87-11e5-8940-febca143c63c.png)

With this option:
```
scope.options = {
          axes: {
            x: {type: 'linear', min: 0, max: 23}
          },
          series: [
            {
              y: "val",
              label: "A line sinusoid",
              color: "#1f77b4",
              type: "column"
            }
          ]
        };
```

**Comment by chaosmail** [comment]
Hi @jpagand 
unfortunately we estimate the width of the columns by the number of columns on the axis - regardless of the current extent. Thanks for reporting this, we will try to fix this as soon as possible.

Best,
Christoph
