### ISSUE TITLE
y axis doesn't display properly when plotting the function y=0

### ISSUE THREAD

**Issue by francescadamico** [n3-charts/line-chart#256]
Every day I have to plot the cumulative rain of a certain geographic area. Fortunately it doesn't rain every day and sometimes my application just ends up by plotting the function y=0. 
The problem is that the y axis completely disappears. 
Any idea how to solve this?
Thanks
Francesca

**Comment by chaosmail** [comment]
Hi @francescadamico 
You can avoid this by setting the `max` setting for the y-axis. There are 2 possibilities: either you set it to a fixed upper bound, or you can set it to a "usual" value if the maximum value is 0.

Here is an example for the second solution: [http://plnkr.co/edit/1QxTDfzC6a3Hz4hTT5nt?p=preview](http://plnkr.co/edit/1QxTDfzC6a3Hz4hTT5nt?p=preview)

Let me know if this solves your problem.

Best
Christoph

**Comment by francescadamico** [comment]
I have tried your solution in the simplest way to see if this changes something.
Now the following are my options with min and max set for the y axis but nothing changes. I still have the same issue.

 $scope.options = {
              axes: {
                  x: {key: 'tick', type: 'date'},
                  y: {type: 'linear'}
              },
              /* only one series is displayed by default. Its label will be added after the query is performed */
              series: [
                  {y: 'value1', color: 'steelblue', thickness: '2px', striped: true, min:0, max: 1}
              ], 
              tooltip: {
                  mode: 'scrubber',
                  formatter: function (x, y, series) {
                      return moment(x).format('DD MMMM YYYY, h:mm a') + ' : ' + Math.round(y*100)/100;
                  }
              },
              lineMode: 'linear',
              tension: 0.7,
              drawLegend: true,
              drawDots: false//true
          };

**Comment by chaosmail** [comment]
the `min` and `max` settings need to go to the `axis: { y: ... }` - you put them to the series ;)

**Comment by francescadamico** [comment]
Ups, I was trying to do too many things at the same time ...
Thanks a lot, it worked perfectly!
But maybe it is something that can be fixed be default

**Comment by chaosmail** [comment]
perfect :) yeah this should be fixed definitely.
