### ISSUE TITLE
Titles in the Stacked column series

### ISSUE THREAD

**Issue by MightyPixel** [n3-charts/line-chart#257]
Hello! I want to display a text inside each of the series. Something like this:
![graph_text_suggestion](https://cloud.githubusercontent.com/assets/1314810/8179970/39533692-1423-11e5-9e08-c424a1c1a607.png)

I looked over the params but I don't think there is anything that can do this.
Am I missing something?

Cheers

**Comment by chaosmail** [comment]
Hi @MightyPixel 
As far as I know this is not possible right now. Should these labels be always displayed or just when hovering over?

**Comment by MightyPixel** [comment]
Always displayed is the desired look. Is there a easy way to insert the text in the rects? Maybe d3 or something?

**Comment by chaosmail** [comment]
the text should be the series legend (Data 1, Data 2, Data 3) or the column value (60, 70, 80)? Unfortunately, I cannot think of a quick work-around to achieve this :(

**Comment by chaosmail** [comment]
Hi @MightyPixel 

so I guess what you want to achieve is currently not possible and we are not going to implement sth like this anytime soon. Maybe you can try `tooltip: {mode: 'axes'}` and see if you like it. You could also use some CSS styling to customize the tooltips.

Let me know what you think about this and if you can live with this solution!

Best,
Christoph

**Comment by MightyPixel** [comment]
Thanks for the reply! I decided that I had too much functionality that defers from what the lib provides, so I went with a custom solution :)

Although it would be nice if someday there is a chart that I needed.

*Here is a screen of my custom solution:
![screen shot 2015-06-30 at 4 52 16 pm](https://cloud.githubusercontent.com/assets/1314810/8432391/72b76b4e-1f48-11e5-901b-5785125c9a61.png)

**Comment by chaosmail** [comment]
Hi @MightyPixel 
you are absolutely right, this would be very hard'n'dirty to do this with this lib.
Your solution looks really great, do you consider to publish it on Github? I am sure it could be useful to some people.

Let me close this issue, if you still have any questions don't hesitate to contact us.

Best.
Christoph
