### ISSUE TITLE
redraw chart to fit new contaner div

### ISSUE THREAD

**Issue by lj1000** [n3-charts/line-chart#258]
Hi,

Im using n3-charts line chart within angular-gridster.  

when I resize one of the grids that contains a chart as you would expect the chart does not resize to fit the grid. what I am trying to do is, from within the angular-gridster item resize event , ask the chart to redraw its self so as it will fit the new container size. 
My question is how do I get the chart to redraw itself?

**Comment by chaosmail** [comment]
Hi @lj1000 
currently the chart redraws automatically only on a window resize event (or when options or data changes). However as a work-around, if you know when the resize occurs, you could toggle some random setting (also an invalid one) to force a redraw.
Here is a plunkr to illustrate this: [http://plnkr.co/edit/Ee5Ysa9EGSqcd1KrASsn](http://plnkr.co/edit/Ee5Ysa9EGSqcd1KrASsn?p=preview)
Let me know if this helps you!
Best,
Christoph

**Comment by lj1000** [comment]
Hi Chistoph,

thanks for the speedy reply. 
ill give this a go and let you know how I got on. 

thanks
lj_1000

**Comment by lj1000** [comment]
Hi Chistoph,

It worked like a charm.

Thanks
lj_100
