### ISSUE TITLE
Axis string labels?

### ISSUE THREAD

**Issue by dorlandode** [n3-charts/line-chart#263]
This may be a dumb question, but I am not able to figure out how to use a string as the axis tick mark labels.  All the examples show numbers in both the x and y axis, I would like the ticks on the y axis to be numeric and the x axis to be text, for example a country name.  Do i do this with a custom tickFormatter?

**Comment by chaosmail** [comment]
It's not dumb; yes, you would use a function as `ticksFormatter` option to transform a number to a label.

**Comment by marshall007** [comment]
@chaosmail would it be possible to support this out of the box? It seems like you should be able to specify a string field as the x-axis `key` and everything would "just work".

**Comment by chaosmail** [comment]
yeah, this would make a lot of sense for bar charts

**Comment by marshall007** [comment]
@chaosmail I think the solution is to modify `n3utils.getPseudoColumns()` to properly return string-based keys but I'm not sure there's a straight-forward way to do this. Currently that function doesn't look at the values in each series to compute the set of keys, but I think that's what we'd have to start doing. Any thoughts?

**Comment by chaosmail** [comment]
I think it would be best to integrate this into `src/utils/scales.coffee`; to allow an additional option `ticksKey`. If this options is set, we could return an array of ticks extracted by this key from the data set and apply them directly on the axes.
Let me know if you need guidance if you want to implement this ;)

**Comment by marshall007** [comment]
@chaosmail unless I'm missing something, I don't think it's quite that simple. There are still underlying issues with having string keys in your data aside from setting `axis.ticks()` correctly in `n3utils.createAxis()`. For example, the following configuration doesn't work today:

```js
var options = {
  axes: {
    x: { key: 'x', ticks: [ 'GROUP1', 'GROUP2' ] }
  },
  series: [{
    y: 'value'
    type: 'column'
  }]
};

var data = [
  { x: 'GROUP1', value: 23 },
  { x: 'GROUP2', value: 42 }
];```

**Comment by lorem--ipsum** [comment]
Hey, we're closing this because it's been a while and we're trying to avoid zombie issues. If the problem persists, please open a new issue (and don't forget, your issue is much more likely to be fixed if you provide a working [CodePen](http://n3-charts.github.io/line-chart/#/examples) : easier for us, faster for you !).

Thanks again for helping us making n3-charts awesome.

--
_Sébastien & Christoph_
