### ISSUE TITLE
Scroll to make graph larger

### ISSUE THREAD

**Issue by BinaryWasteland** [n3-charts/line-chart#267]
Just looking at C3 and when a graph is generated the user can hover inside where the bars or line graph is and scroll the mouse wheel and the graph expands to give you a more granular look. I could see this being useful for graphs that have 90 days worth of data and 7 bar graphs per day. Not sure how hard it would be to implement?

**Comment by chaosmail** [comment]
Hi @BinaryWasteland 
we are planning this for the 2.x release.
Best,
Christoph

**Comment by BinaryWasteland** [comment]
Amazing! Going to make my C-levels very happy. Amazing work by the way!

**Comment by chaosmail** [comment]
Hi @BinaryWasteland
we added zooming and panning in the master branch.
Best,
Christoph

**Comment by BinaryWasteland** [comment]
Your Awesome! I was following the convo on this. Did you decide on the reset button?

**Comment by chaosmail** [comment]
Yeah, we have a little zoom-out icon now to reset to the original view.
You can check it out here ;) http://plnkr.co/edit/ewHIITSFoHfIXDxEN7tp?p=preview
Let us know what you think!

**Comment by BinaryWasteland** [comment]
@chaosmail When is this expected to be versioned so I can bower update n3?
