### ISSUE TITLE
tooltip box size

### ISSUE THREAD

**Issue by lj1000** [n3-charts/line-chart#269]
Hi all,

is there a way to increase the the size of the box for the tooltip. I increased the text font size using 

.scrubberText {
  font-size: 22px;	
}

which increased the size of the text correctly but now I need to increase the size of the box as the text is cut off at the top.

cheers lj1000

**Comment by chaosmail** [comment]
Hi @lj1000 

you could try to add bigger margins with the `margin` option to the svg.

```
$scope.options = {
  margin: {
    top: 100,
   bottom: 100
  }
}
```

Let me know if this helps!

Best,
Christoph

**Comment by lj1000** [comment]
Hi Christoph,

gave it a try. it squashed the size of the complete graph but had no affect on the tooltip box size.
Inspecting the tooltip box in the developer tools in chrome I noticed the class attached to it is 'scrubberItem'. I tried setting a height property on this but it had no effect. 

Do you know where/how the height of the tooltip box is calculated?

Thanks
lj1000

**Comment by chaosmail** [comment]
Hi @lj1000 
ahhh I see your point. You could try to override the `scrubberItem` attributes with the `!important` attribute.
Best,
Christoph

**Comment by lj1000** [comment]
Hi Christoph,

Gave it a try but height still stayed same. 

The largest you can change the font size to in scrubberText and still have the text still fit nicely in the box is 16px. That's fine for my purposes.
 
Thanks
lj1000
