### ISSUE TITLE
adding click event

### ISSUE THREAD

**Issue by lj1000** [n3-charts/line-chart#270]
Hi,

I am trying to add drill down functionality to my chart.
What I mean is when the use clicks on a bar (or point) ill reload the chart with different 'lower level' data.
I am using tooltip modes 'scrubber' as I need to format the x-axis value before displaying it and also we want the tooltip to display above bar/at point which works great. 
The problem ive come up against is that the docs say there is a build in click event but only when not using a tooltip with mode scrubber.

Has anyone solved a similar problem of adding a click event to a chart with tooltip scrubber or any suggestions how to go about doing this?

Thanks
lj1000

**Comment by MattiSG** [comment]
Hi @lj1000. It is unfortunately not possible to do this for the moment, as:

> In the current implementation a transparent rectangle is drawn over the whole chart. This makes it impossible to detect or propagate these click or hover events.
> We introduced the on-focus event for scrubber mode, that returns the currently highlighted data point.

(quoting @chaosmail from Gitter)

I would also have a use for this.

**Comment by lj1000** [comment]
Hi MattiSG,

Thanks for the reply.
It looks like its impossible in its current implementation then to add click events. 
Ill see if I can do something using the on-focus event  to meet my needs.
If I get anywhere ill let you know.

cheers,
lj1000
