### ISSUE TITLE
Handling of null y values

### ISSUE THREAD

**Issue by teledemic** [n3-charts/line-chart#275]
Nulls on either end of the range work great - the line starts / ends at the first / last non-null value. I have two problems though:
* It would be swell if lines didn't interpolate over null values, but ended and restarted just like at the outside. In other words, this dataset:
```
    {x: 4, y: 40},
    {x: 5, y: null},
    {x: 6, y: null},
    {x: 7, y: 50},
```
is different than this one:
```
    {x: 4, y: 40},
    {x: 7, y: 50},
```
but I can see how that might beyond the scope of this project

* The simpler and less controversial problem is that for a dataset that happens to have **only** null y values, console errors will be thrown for all mouse movements as the scrubber tries to find the values.

Here's a plunker that shows both cases:
http://plnkr.co/edit/W7UK8ITaX2CrW4RBT4Lb

**Comment by chaosmail** [comment]
Thanks for reporting this error!
I think it might be best to remove `null` values from the dataset, what do you think @lorem--ipsum? Another (not really correct) solution would be to replace `null` values with a `0` values.

**Comment by lorem--ipsum** [comment]
Hmmm replacing `null` with `0` wouldn't solve the problem, would it ? Making the difference between absent data and interrupted data is always hard, and usually ends up being solved by a good convention :-)

I suggest using `NaN` for empty rows (i.e. rows that should be drawn) and `null` for rows that should be interpolated over. We'll keep this as a reference for 2.0. Thoughts, guys ?

**Comment by 2110634** [comment]
Sorry for digging this issue but is there any solution for this? 
My dataset as some NaN values. Is there a way to fix the occurrence of the error in the developer browser console "<path> attribute d: Expected number, "…09141116,0L1512,NaNL1512,531.428…"."

**Comment by chaosmail** [comment]
@2110634 
if you have NULL values in your dataset, why don't you remove (filter) them or modify (map) them to 0? 

The error that you mention is very likely due to some bug in your data - maybe you can copy a subset of your datasample to this codepen http://codepen.io/chaosmail/details/ZQMjdN/ in order to reproduce the problem.

**Comment by pedrokost** [comment]
I am also affected by this bug/feature. Null data means "there is no data" and not that the dataset is invalid. Take for example a dataset of temperatures between June and November, where there is no data available for July. Displaying 0 would be incorrect (a temperature of 0 has a meaning). Interpolating between the last value of June and the first of August, as the library currently does, is also incorrect.

The only correct way to handle such cases is to show a gap on the line graph where there are null values.

**Comment by lorem--ipsum** [comment]
Series' options have a `defined` property that solves this exact problem. It's basically a shortcut to [this](https://github.com/d3/d3/wiki/SVG-Shapes#line_defined). You can see an example of its usage on the [examples page](http://n3-charts.github.io/line-chart/#/examples) (look for the example called "Interrupted data").
