### ISSUE TITLE
onClick, onHover events

### ISSUE THREAD

**Issue by dorlandode** [n3-charts/line-chart#277]
Is there a reason the onClick and onHover events only work when the tooltip mode is axes and none?  I would think this would be needed when the mode is scrubber too.  

What are your thoughts?

**Comment by chaosmail** [comment]
Hi @dorlandode 
please see my comment here https://github.com/n3-charts/line-chart/pull/221#issuecomment-120565810
Best,
Christoph

**Comment by chaosmail** [comment]
If there is no updated on this issue, I will close it for now.
