### ISSUE TITLE
Labels on x axis not lining up on column chart

### ISSUE THREAD

**Issue by dorlandode** [n3-charts/line-chart#278]
I have a column chart I am loading after the page loads.  In other words, I fire off an http request to get the data to bind to the chart.

When the data comes back, the x axis labels, which I am generating using the ticksFormatter function, are not lining up vertically with the columns on the chart.  The first label appears to be a position 0, meaning left aligned to the y axis.  The other labels are equidistant, but not lined up with the columns.

My options look like this:
```
$scope.options = {
    axes: {
        x: {
            key: "x",
            ticksFormatter: function (d, i) {
                var test = "";
                if ($scope.data[i] != undefined) {
                    test = "foo" + i;
                }
                return test;
            },
            ticksRotate: 10
        }
    },
    series: [
      {
          y: "val_0",
          label: "Foos",
          color: "#7BADD0",
          type: "column"
      }
    ],
    tooltip: {
        mode: 'scrubber',
        formatter: function (x, y, series) {
            return $scope.data[x].label + " " + $scope.data[x].val_0;
        }
    },
    drawLegend: true,
    drawDots: true,
    hideOverflow: false
};
```
The data is an array of {x: 0, val_0: [some number]} objects.
![example](https://cloud.githubusercontent.com/assets/1105035/8632104/25ed2c18-274a-11e5-9623-77d34b5566f7.png)

**Comment by chaosmail** [comment]
Hi @dorlandode 
Here is a working example of text labels on a bar chart [http://codepen.io/anon/pen/qdVPdK](http://codepen.io/anon/pen/qdVPdK). Hope that helps!
Let me know if you have still problems!
Best,
Christoph

**Comment by chaosmail** [comment]
Hi  @dorlandode 
what is the status on this issue? did you manage to get it to work?
Best,
Christoph

**Comment by chaosmail** [comment]
I will close this, please let me know if there are any more issues!
