### ISSUE TITLE
Having issue with bars overlapping each other

### ISSUE THREAD

**Issue by BinaryWasteland** [n3-charts/line-chart#283]
I am using N3 to plot shift data as well as daily totals. the daily totals come up fine but the shifts come up as overlapping each other as seen below:

![screen shot 2015-07-27 at 1 15 16 pm](https://cloud.githubusercontent.com/assets/1633320/8912606/b9d9bf58-3461-11e5-9958-67211365ac78.jpg)

If i use the running totals (average line) it seems to space them correctly as seen below:

![screen shot 2015-07-27 at 1 15 04 pm](https://cloud.githubusercontent.com/assets/1633320/8912617/d07f0394-3461-11e5-96ca-329729043aa0.jpg)

The only thing I can think of is I use the same value for X in both the totals and the shifts but I am not 100% sure why that would cause this. Any help is appreciated :)

Thanks,

Greg

**Comment by chaosmail** [comment]
Hi Greg,
thanks for reporting the issue! Could you create a Plunkr/CodePen to help me to debug this problem?
Best,
Christoph

**Comment by BinaryWasteland** [comment]
This is as good as I could get it. I have options before generating and options2 is what is there after generating. the data is just a snapshot that I pasted in. They overlap different on codepen but still overlap:

http://codepen.io/BinaryWasteland/pen/qdQWjL

**Comment by chaosmail** [comment]
Thanks a lot,

![bildschirmfoto vom 2015-07-27 21 36 14](https://cloud.githubusercontent.com/assets/2969388/8915821/8fd8a764-34a7-11e5-8635-791dd563a934.png)


I created a little snippet to convert your date strings into date objects and then filter for valid date objects.
```
var data = [...];
$scope.data = data.map(function(d){
  // Create a valid date
  d.x = new Date(d.x);
  return d;
}).filter(function(d){
  // Filter data points with valid dates
  return d.x;
});
```

Here is the working demo: http://codepen.io/chaosmail/pen/QbJLav

Best,
Christoph

**Comment by BinaryWasteland** [comment]
Ok so all you need to do to see my issue is change options to options2 and unclick the average and my issue is reproduced on yours. Also, is here:

http://codepen.io/BinaryWasteland/pen/qdQWjL

**Comment by BinaryWasteland** [comment]
Also, Thanks for the sweet function for Date objects! I didnt think of that

**Comment by chaosmail** [comment]
Thanks again for creating the CodePen - it was quite easy to find the error with your help. I fixed it and proposed a PR to solve this issue; it should be merged in the next version.
Here is a CodePen with the fixed PR (just for reference - not for production): http://codepen.io/chaosmail/pen/WvYNRJ

**Comment by BinaryWasteland** [comment]
Thanks @chaosmail! Works awesome. Just copied the .min to my project until the next release incorporates it :)
