### ISSUE TITLE
Vanishing Stacks On Long Queries

### ISSUE THREAD

**Issue by BinaryWasteland** [n3-charts/line-chart#284]
So after updating the code to the one in the plunkr @chaosmail sent, I tried doing a query of 2 months worth of data (by day) and the bars seem to get so small they become negative values. Please see the images below:

![screen shot 2015-07-28 at 2 29 26 pm](https://cloud.githubusercontent.com/assets/1633320/8939936/4cf799bc-3535-11e5-8233-75e10bc43b7c.jpg)
![screen shot 2015-07-28 at 2 29 14 pm](https://cloud.githubusercontent.com/assets/1633320/8939937/4cfdd296-3535-11e5-95fa-6960d18903a6.jpg)

This is an example of it on codepen:
http://codepen.io/BinaryWasteland/pen/VLVPoW

**Comment by chaosmail** [comment]
Hi Greg,

thanks for reporting this issue. I updated the PR to fix this bug (the url of the branch is still the same). Let me know if this works for you (in the same CodePen). Here is a fork http://codepen.io/chaosmail/pen/YXRZEL

Please note, that these changes are untested so far and will not be merged into the master before we wrote the appropriate unit and integration tests.

Best,
Christoph

**Comment by BinaryWasteland** [comment]
@chaosmail This is great. Understood for untested. They still shrink but then pop back. I am on the issues board so much I feel like I should try and contribute something to this project :)

**Comment by chaosmail** [comment]
you should try to adjust your `columnsHGap` value, this "pop back" might happen when the width for the columns is smaller than the `columnsHGap`.
Yeah, being active on the issues is actually also helping a lot. If you want to dig into the code then let me know, so I can help/assist you to get started.
