### ISSUE TITLE
Wrong date range displayed when array of dates has only one item

### ISSUE THREAD

**Issue by yarick333** [n3-charts/line-chart#285]
If only one item of type Date is presented in $scope.data the x-axis doesn`t show it but instead shows weird date range of year 1980 to 2060.

A few examples of code:
http://jsfiddle.net/n5qsgb9e/3/
http://codepen.io/anon/pen/GJwdKy

**Comment by chaosmail** [comment]
Hi @yarick333 
thanks for reporting this issue! 

When there is just one element in the dataset the `min` and `max` values of this dataset are the same. Therefore, we try to "center" your datapoint and assume a `min` value of `0` and a `max` value of `2*x` - which is completely wrong (in so many ways) for `Date` objects.

I will see how we can fix this! For now, setting the `min` and `max` options manually would be a workaround.

Best,
Christoph
