### ISSUE TITLE
xAxis extra ticks on either side

### ISSUE THREAD

**Issue by sawajid** [n3-charts/line-chart#292]
In my chart I'm getting extra ticks on either side of x-axis.
here is the codepen http://codepen.io/sawajid/pen/oXmdvX/
I added 
$scope.ticks = $scope.data.map(function(d) {
        return d.x;
      });

and in the axes i put,  ticks: $scope.ticks
still the issue remains

can anyone point to what am i doing wrong ?

**Comment by chaosmail** [comment]
If you specify the type `column` we add an additional empty data point to the data array; this is not very clean and we should make this better (or optional) - however I guess this is the reason for your problem. maybe setting the `min` and `max` option could solve this as a workaround

**Comment by sawajid** [comment]
Thanks chaosmail.
adding 
min: new Date(2015, 05, 2), max: new Date(2015, 11, 31)
solved my issue
