### ISSUE TITLE
Remove 'resize' eventListener on destroy directive

### ISSUE THREAD

**Issue by chemdnepr** [n3-charts/line-chart#294]
There is an issue, when directive is destroyed 'resize' eventListener is not destroyed.

**Comment by chaosmail** [comment]
Hi @chemdnepr 
thanks for reporting this issue - I know we have this fixed in new the `dev` channel (however, it will take some time until we can release this)! I will evaluate this problem for the current version and get back to you soon.
Best,
Christoph
