### ISSUE TITLE
Compatability with n3-pie-charts

### ISSUE THREAD

**Issue by blairconner** [n3-charts/line-chart#295]
Hello,

I'd like to include both the n3-line-chart and n3-pie-chart, but when I try to add the pie chart module both stop working. I can choose one or the other. So far as I can tell there is a mismatch in  the angular versions used by each module. 

Is there any way for both modules to function correctly when using angularjs? 

Thank you!

Best regards,
Blair

**Comment by chaosmail** [comment]
Hi Blair,
thanks for reporting this issue! I will try to figure this out and come back to you soon.
Best,
Christoph

**Comment by chaosmail** [comment]
Did you install them with bower? It looks like pie-charts is requiring the ancient Angular `1.0.6` whereas line-charts picks the most recent one `1.4.3`.

**Comment by chaosmail** [comment]
I crated a https://github.com/n3-charts/pie-chart/pull/15 to fix the version missmatch.
could you try to run `bower install angular#1.4.3` in your project and see if this fixes your problems?

**Comment by blairconner** [comment]
Yes, I installed them using bower. I tried specifying the angular version and that did not fix the problem.

**Comment by blairconner** [comment]
Any other ideas to get them working together?

**Comment by chaosmail** [comment]
Hi @blairconner 
sorry for taking ages on this! I will give a close look today - once we found the problem it should be fixed very quickly.
Best,
Christoph

**Comment by chaosmail** [comment]
Hi Blair,

using the latest (master) versions, I have no problems displaying both line-charts and pie-charts.
Here is a demo: http://plnkr.co/edit/YPiMJTvCtFQwr5VVGf2T?p=preview

Best.
Christoph

**Comment by blairconner** [comment]
Hi Chris,

Glad to hear that it's working. Could you confirm the versions for me?

Regards,
Blair

**Comment by chaosmail** [comment]
Hi Blair,
I think most important would be the latest stable Angular version. You can check in your `bower_components` directory, the `angular/package.json` file for the current version.
Then you can safely update to the master branch of n3-pie-charts and keep the current version of n3-line-chart (although there are some cool features in the master, but better wait for the stable release).

Let me know if you need further help!

Best,
Christoph

**Comment by chaosmail** [comment]
Hope everything is working for you!
