### ISSUE TITLE
Notify hover on and off

### ISSUE THREAD

**Issue by HarelM** [n3-charts/line-chart#297]
Hi, First and foremost great project!
I wanted to know if the following is possible:
I have a chart displaying the height graph of a cycling route.
the route is displayed on a map next to the chart.
I would like the user to be able to hover on the chart and while doing so the relevant map location would be highlighted as well.
so basically what I need is hover-in, hover-out and hover-changed, is there anything like it currently?

**Comment by chaosmail** [comment]
Hi @HarelM 

we currently support the [`hover`](https://github.com/n3-charts/line-chart#hover) event via the attribute `on-hover` for tooltip mode `axes` or `none`.

Here is an example: http://plnkr.co/edit/lToz6E6vAsXqSiIBmiIM?p=preview

Let me if this helps you; if not, adding `hover-in` and `hover-out`events should be easy.

Best,
Christoph

**Comment by HarelM** [comment]
I have tried ```on-hover``` but it does not let me know when the mouse is no longer on any point...
I do like the ```scrubber ``` for presenting tooltip so I would be happy if you could support ```hover-in``` and ```hover-out``` for every point on the chart regardless of the tooltip mode.
Thanks for the prompt response!
