### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by kevinkasper** [n3-charts/line-chart#305]
Hello,

i use n3-charts with Twitter Bootstrap, but the chart doesn't resize, when the window is resizing.

    <div class="row">
        <div class="col-md-3">
            <linechart data="data" options="options"></linechart>
        </div>
    </div>

**Comment by chaosmail** [comment]
Hi @kevinkasper 
here is an example using bootstrap http://embed.plnkr.co/nxFt1XnkJVa0dtoNA8J8/preview
This should work fine if you set the `height` attribute manually.

Let me know if this helps!

Best,
Christoph

**Comment by kevinkasper** [comment]
Hi @chaosmail 
thanks for quick reply. It works fine.

Best,
Kevin

**Comment by chaosmail** [comment]
Nice, please let me know if there are any other problems!
Best,
Christoph
