### ISSUE TITLE
Ticks overlap when resize browser

### ISSUE THREAD

**Issue by yarick333** [n3-charts/line-chart#306]
Ticks overlap when reducing the width of the browser
![_002](https://cloud.githubusercontent.com/assets/12997483/9444227/18b43494-4a8e-11e5-92d5-f2dac71782f6.png)
![_001](https://cloud.githubusercontent.com/assets/12997483/9444228/18b95136-4a8e-11e5-8cf8-c1aef74c11db.png)

**Comment by chaosmail** [comment]
Hi @yarick333 
the number of ticks is estimated by the number of points that you are displaying. You can solve this provlem in different ways:

* Create a bigger margin on the bottom and rotate the ticks by 30 degree
* Use less tick values by defining the `ticks`
* Use less tick values by defining the `tickInterval`

Let me know how we can solve this problem!

Best,
Christoph

**Comment by chaosmail** [comment]
Here is an example using `ticksRotate` and `ticks` together: http://plnkr.co/edit/j2KAcfI3Givae7ce4A2o?p=preview

**Comment by chaosmail** [comment]
Here are the time intervals that can be used for `ticksInterval`: https://github.com/mbostock/d3/wiki/Time-Intervals#intervals
you would use them like this: https://github.com/mbostock/d3/wiki/Time-Scales#ticks

**Comment by yarick333** [comment]
Using the definition of ticks is not suitable for a large range of data. For example range (01/01/2015 - 2015-31-12). http://plnkr.co/edit/7MG8VX?p=preview
Rotate ticks inadmissible on project requirements =(.
Time intervals have bag. If set ticksInterval it will show the beginning of the month. It is not necessary.
http://codepen.io/anon/pen/Qbevwg
![_003](https://cloud.githubusercontent.com/assets/12997483/9445166/59c3d2fa-4a93-11e5-9bd1-2818f6051da2.png)

**Comment by yarick333** [comment]
Sorry if I have some mistakes in grammar =).

**Comment by chaosmail** [comment]
So maybe you could combine `ticksInterval` with `ticksFormat` (or even `ticksFormatter` to be super flexible)

**Comment by yarick333** [comment]
I still can not understand how to do it =(

**Comment by chaosmail** [comment]
Sorry, I am on the phone that's why I didn't explain the solution further.

First, I think that in your case d3.time intervals can solve your problem. However, now we need to fix/hide the months that are showing up.

To do so, we could use the `ticksFormat` option. It accepts a [d3.time.format](https://github.com/mbostock/d3/wiki//Time-Formatting) String; so we could try to format all tick values to the desired format.

**Comment by chaosmail** [comment]
If this doesn't solve the problem, you could use the `ticksFormatter` option. It accepts a function with one argument `x` and needs to return a String. I will show you a demo later.

**Comment by chaosmail** [comment]
Here is a demo using the `ticksFormatter` function: http://codepen.io/chaosmail/pen/OVKvEB

**Comment by yarick333** [comment]
Hmm... an interesting option. Maybe possible to make that interval does not end at the month end and continued on?
![_004](https://cloud.githubusercontent.com/assets/12997483/9466837/4d7b5682-4b40-11e5-968f-f81852b03ec1.png)

**Comment by yarick333** [comment]
I did it! I used <code>axis.tickValues([1,2,4])</code> to specify the actual tick marks that should appear.

**Comment by chaosmail** [comment]
Wow, great. Even I didn't know about this :)
