### ISSUE TITLE
Rotate colors?

### ISSUE THREAD

**Issue by aquila** [n3-charts/line-chart#307]
Is there a way to rotate colours from a set, so e.g. the first bar is coloured red the next green and then back red again? Or should I hack something in (and submit a pull request)?

**Comment by chaosmail** [comment]
You can use conditional coloring by providing a function instead of a color in the series. The function receices 2 arguments (d the data point and i the index of the point in the data set) and needs to return a color string.

**Comment by aquila** [comment]
Great, thanks a lot!
