### ISSUE TITLE
Move y-origin for charts?

### ISSUE THREAD

**Issue by aquila** [n3-charts/line-chart#310]
I would like to plot data where the Y-axis starts at -90, so for a column type all columns should start at -90 and go up (instead of going down from 0 for negative values and going up from 0 for positive values). Is this possible, to move the Y-origin?

**Comment by chaosmail** [comment]
this is currently not possible. however, you could use the `ticksFormatter` and the `tooltip: { formatter }` option to modify the ticks and tooltips - such that you map them to a different range. but this is a very dirty hack.

```js
var shift = 90;
var xFormat = d3.format('g');
var yFormat = d3.format('.2f');
var yMap = function(y){ return yFormat(y-shift); };
var yMapInversed = function(y){ return y+shift; };
$scope.options = {
  ...
  axis: {
    x: {ticksFormatter: xFormat},
    y: {ticksFormatter: yMap}
  },
  tooltip: {
    formatter: function(x, y, series) { return xFormat(x) + ": " + yMap(y); }
  }
};
var data = [ ... ];
$scope.data = data.map(function(d){
  d.y = yMapInversed(d.y);
  return d;
});
```

**Comment by aquila** [comment]
Works perfectly, thanks!
(One minor comment for future readers: the option axis should read axes, otherwise little will happen. That's what I discovered after a nice debugging session.)

**Comment by chaosmail** [comment]
nice, thanks for the hint :D yeah I am always confusing is and es
