### ISSUE TITLE
duplication of labels in the X axis

### ISSUE THREAD

**Issue by nicolabortignon** [n3-charts/line-chart#314]
Given this data
```
[{"235":72.85,"x":"2015-08-27T07:00:00.000Z"}]
```

and this options setup:
```
        $scope.options = {
          margin: {
            right: 30,
            top: 20,
          },
          stacks: [{
            axis: "y",
            series: labels.map(function(obj) {
              return obj.name;
            })
          }],
          axes: {
            x: {
              zoomable: false,
              type: 'date',
              ticksFormat: '%B',
              ticks: d3.time.months,
              ticksRotate: 0
            },
            y: {
              zoomable: true,
              ticksFormat: '.2f',
              ticks: 5,
              min: 0
            }
          },
          tooltip: {
            mode: 'scrubber',
            formatter: function(x, y, series) {

              return moment(x).format("Do MMM, dddd") + " " + y + " " + series.label;
            }
          },
          lineMode: "cardinal",
          series: series,
          columnsHGap: 0,
        }
```
I experience this weird repetition in the x axis labels space

![screen shot 2015-08-28 at 6 49 44 pm](https://cloud.githubusercontent.com/assets/883459/9560003/a5f8976c-4db5-11e5-8906-e5d43164acd8.png)

**Comment by chaosmail** [comment]
Hi Niccola,

I think this problem occurs when you display a bar chart with only 1 data point on a time-series axis. We try to "center" the column by using the [0; 2*x] range - which results in bad intervals for time-series [~1970; ~2020]. We need to fix this.

A workaround is to use `min` and `max` attributes for the x-axis or more than 1 data points for the data set. If you still have problems with overlapping x-labels, you can also take a look at our small FAQ section in the WIKI https://github.com/n3-charts/line-chart/wiki/FAQ

Best,
Christoph
