### ISSUE TITLE
Container size change issues

### ISSUE THREAD

**Issue by HarelM** [n3-charts/line-chart#315]
Hi, 
I'm trying to do the following and having a hard time:
I want to place the chart on  a bootstrap tooltip/popover in order to show and hide it according to user demand.
I want to be able to move the chart and resize the panel, when I tried to do so I encountered the following issues:
1. When the container size changes the chart does not get refreshed, I needed to manually call ```window.dispatchEvent(new Event('resize'));```
2. When moving the panel that the graph is on the tooltip for the point staies behind rendering the "scrubber" useless.

Help/instructions how to do it are welcome.
I used InteractJS in order to be able to move and resize the panel for the chart.

**Comment by chaosmail** [comment]
Hi @HarelM
 
thanks for reporting this issue. it would be very helpful if you could create a small plunkr demo to illustrate your problem, you could start from this one: http://plnkr.co/edit/xVPPr3DRIYMM8NmoBrNw?p=preview

Best,
Christoph

**Comment by HarelM** [comment]
I hope this worked:
http://plnkr.co/edit/2ploOpwIXC9yJdKIEzZD?p=preview
Please drag the chart away from its original location and try tooltiping on one of the points.

**Comment by chaosmail** [comment]
Hi @HarelM 
I looked into your issue in detail, and this is what I came up with.

1. It seems, that Interact.js is not triggering a `resize` event (but a non standard `resizemove`). And also n3-line-charts is not listening for resize events on the parent container (just on window). I fixed this, I added a resize event on the `target` element in the `resizemove` handler and implemented an event listener for resize events in n3 http://plnkr.co/edit/Ben7HsVAPcpDJdzw5etD?p=preview I will propose a PR once we agree that this is the right way.

2. When I go crazy with moving and resizing the panel, the scrubber still says the same (I am using Chromium btw). Are you still facing this problem, and if yes, which browser are you using? Are there any errors in the console?

Best,
Christoph

**Comment by HarelM** [comment]
Hi Chris,
Thanks for taking the time to investigate it.
I'm using Firefox. I can still see an issue with the mouse location and scrubber in your plunker so I'm not sure if it's fixed or not.
The further away I drag it the worse the scrubber is.
I know interactjs has an issue with resize, but note that my code fires a resize window when the moveend of interactjs is fired.

**Comment by chaosmail** [comment]
Yeah, I saw that. I replaced this window resize event with a resize event on the target (container) itself and extended n3-line-chart, that it also listens to this event. So if this is a good solution, we just need to make sure (or make a PR), that Interact.js also fires a redraw event (or we need to keep the trigger in the function).

Interesting, the scrubber position seems to be Firefox problem. I will see how this can be fixed.

**Comment by chaosmail** [comment]
Hi @HarelM 
I found the error; seems like that in the Interact.js demo the use the webkitTransform attribute to modify the position of the div container of the dragable element. This causes the browser to not compute the proper relative coordinates. So i replaced this attribute with the common `left` and `top` styles - then everything is working fine.
Here is a working demo: http://plnkr.co/edit/55k4joa2JWOIwrKa3Olv?p=preview

Best,
Christoph

**Comment by HarelM** [comment]
Thanks!
