### ISSUE TITLE
Tooltip overlaps when values are close, but not too close

### ISSUE THREAD

**Issue by smoksnes** [n3-charts/line-chart#316]
When the values are close, but not too close the tooltips tend to overlap.

Example with type linear:
http://plnkr.co/edit/JUSOaGEFrjnUh3UNK4ZI?p=preview

In the supplied example it works for x == 2, but not when x == 1.
```
  {
    x: 1,
    val_0: 100000,
    val_1: 100400,
    val_2: 120600,
    val_3: 130800
  },
  {
    x: 2,
    val_0: 100000,
    val_1: 100000,
    val_2: 100000,
    val_3: 100000
  },
```

Example with type log:
http://plnkr.co/edit/abIzoEjSLWTM9TkjamII?p=preview

In the supplied example it works for x == 5. However, when x == 6 or x ==7 the tooltips overlap.
```
 {
    x: 5,
    val_0: 100000,
    val_1: 110000,
    val_2: 120000,
    val_3: 130000
  },
  {
    x: 6,
    val_0: 290000,
    val_1: 340000,
    val_2: 390000,
    val_3: 550000
  },
  {
    x: 7,
    val_0: 250780,
    val_1: 350780,
    val_2: 450780,
    val_3: 550780
  },
```

**Comment by chaosmail** [comment]
hi @smoksnes 
thanks for reporting this issue and the creating the illustrating demos (this really helps a lot). I will take a look at this problem and get back to you as soon we have found a solution.
Best,
Christoph
