### ISSUE TITLE
Can I change font of chart?

### ISSUE THREAD

**Issue by truyen93** [n3-charts/line-chart#318]
n3 line chart is A awsome chart but I don't like it's font. Can I change it by option?

**Comment by chaosmail** [comment]
Hi @truyen93 
sure you can use any font you like by defining it via CSS, here is a demo http://plnkr.co/edit/qVKKnbywFAELLh2QWzem?p=preview
Best,
Christoph

**Comment by truyen93** [comment]
Thank @chaosmail  :+1:
