### ISSUE TITLE
Can I rolate x label chart?

### ISSUE THREAD

**Issue by truyen93** [n3-charts/line-chart#319]
my x label is date so it's so long :(. 
Thank!

**Comment by chaosmail** [comment]
sure, here is a demo http://plnkr.co/edit/j2KAcfI3Givae7ce4A2o?p=preview

**Comment by truyen93** [comment]
thank @chaosmail. Sorry if I bothers you!

**Comment by chaosmail** [comment]
@truyen93 this doesn't bother me at all, you are always welcome to ask questions if you are stucked or if you found a bug :)
thanks for using n3-line-charts btw. people like you are the reason why we are working on this library

**Comment by truyen93** [comment]
thank @chaosmail I seem that my chart was duplicate x label twice (it's date type). 
Do you have any ideal?
my data: 
$scope.dataTest = [{
                  "hits" : 41559,
                  "sum_unBlendedCost" : "868.8720307299947",
                  "avg_blendedRate" : "0.0542105187318246",
                  "key" : 1438387200000,
                  "sum_blendedCost" : "859.3602748399655"
                }, {
                  "hits" : 41974,
                  "sum_unBlendedCost" : "1005.5889742999409",
                  "avg_blendedRate" : "0.055651289718932094",
                  "key" : 1438473600000,
                  "sum_blendedCost" : "976.9996922699304"
                }, {
                  "hits" : 44481,
                  "sum_unBlendedCost" : "938.18124664995",
                  "avg_blendedRate" : "0.05294738550402792",
                  "key" : 1438560000000,
                  "sum_blendedCost" : "907.1317417899413"
            }];

**Comment by truyen93** [comment]
ops. I fixed that by set ticks. It's ok if ticks not equal 6 :+1:

**Comment by chaosmail** [comment]
alright, here I put together some cool tick formatting and interval features http://plnkr.co/edit/Ujl3eqAkInFRwxxCUhHI?p=preview
