### ISSUE TITLE
onClick event

### ISSUE THREAD

**Issue by PoOoZaQ** [n3-charts/line-chart#324]
According to the readme I can implement custom events such as onClick.
I can't seem to manage to do so, here is an example codepen from one of the example's I've edited a bit:

http://codepen.io/anon/pen/NGqNwP

I don't see any events regarding the click get triggered in the code.

**Comment by chaosmail** [comment]
Hi @PoOoZaQ 
Unfortunately, click events work only in tooltip mode `axes` (not in `scrubber`) when a user clicks on dots or columns. Therefore you need to also set `drawDots` to true in your example. Here is a working example: http://codepen.io/anon/pen/PPZMVj
Best,
Christoph
