### ISSUE TITLE
no grouped column chart it appears

### ISSUE THREAD

**Issue by jlmagee** [n3-charts/line-chart#332]
When I wanted to use this about a year ago, it was not possible because I required grouped columns. See http://bl.ocks.org/mbostock/3887051 for an example, I'll also need to draw plain line charts on a secondary Y axis. This is not an immediate need for me but it would really fill out the offering.

**Comment by chaosmail** [comment]
Hi @jlmagee 
take a look at this http://embed.plnkr.co/QmyBRHMA1gi0bkbBA05A/preview
Best,
Christoph

**Comment by jlmagee** [comment]
Thanks. Looks good. I'll study more in a while.
