### ISSUE TITLE
Panning a graph removes rotation from tick labels

### ISSUE THREAD

**Issue by theartofme** [n3-charts/line-chart#336]
If an axis has zoomable: true and ticksRotate set, then the rotation is lost for any elements that scroll off the sides of the graph - new ticks scrolling in have no rotation, and previously-rotated ticks that scroll off and then scroll in again lose their rotation.

**Comment by chaosmail** [comment]
Hi @theartofme 
thanks for reporting this problem, we will try to fix this as soon as possible.
Best,
Christoph
