### ISSUE TITLE
Adjust options to resolutions

### ISSUE THREAD

**Issue by PoOoZaQ** [n3-charts/line-chart#340]
I was wondering if there is some support of adjusting the options to different resolutions.
For example taking this example: http://codepen.io/anon/pen/NGqNwP

The same way the graph adjusts according to it's container width/height, also adjust the ticks of the axes (and perhaps the font-size).

**Comment by chaosmail** [comment]
Hi @PoOoZaQ 

you could use Media Queries in JS with matchMedia or a wrapper like enquire.js. Now you can define breakpoints to make your visualization responsive.

Here is a demo: http://codepen.io/chaosmail/pen/yYgJyq

Best,
Christoph

**Comment by PoOoZaQ** [comment]
And is there a way to cause the line-chart to completely re-draw?
The use-case is when a resolution is changed, I might adjust certain options, and I would want the graph to redraw

**Comment by chaosmail** [comment]
The graph redraws automatically when the options have changed. If you want to redraw the graph without changing options, you could simply toggle some random option:
`$scope.option.someRandomOption = !$scope.option.someRandomOption;`

Best,
Christoph

**Comment by PoOoZaQ** [comment]
Cool thanks
