### ISSUE TITLE
moment not defined, 

### ISSUE THREAD

**Issue by ledikari** [n3-charts/line-chart#347]
I dont know if this is a bug but when i add 

```js
tooltip: {
  mode: "axes",
  interpolate: "true"
  formatter: function (x, y, series) {
    return moment(x).format("MMM Do YY") + ': ' + y;
  }
}
```

encounter this problem in the console of the browser.

**Comment by lorem--ipsum** [comment]
You need to add moment.js as it's not part of our framework. More info here : http://momentjs.com/
