### ISSUE TITLE
When zooming, the plot is expanding beyond y axis.

### ISSUE THREAD

**Issue by mmajews** [n3-charts/line-chart#352]
When I zoom plot (x and y both zoomable ) my plot expanding too much.

Before zoom:
![capturebefore](https://cloud.githubusercontent.com/assets/7868424/10601097/7dc8dff8-770f-11e5-8dad-a4a5b1cd07c7.PNG)
After zoom:
![captureafter](https://cloud.githubusercontent.com/assets/7868424/10601100/7ef488fa-770f-11e5-9b6c-366f77ab2cf3.PNG)

**Comment by chaosmail** [comment]
Hi @mmajews 
you can use the `hideOverflow` option to disable the overflow. Here is a list of all options available: https://github.com/n3-charts/line-chart/wiki/Options
Best,
Christoph
