### ISSUE TITLE
External Zoomer

### ISSUE THREAD

**Issue by nishadotcom** [n3-charts/line-chart#358]
Any chance to have zoom option as vertical bar. As below image
![123](https://cloud.githubusercontent.com/assets/15242739/10811452/2225c77c-7e32-11e5-98d2-dd408c8e86a3.png)

**Comment by chaosmail** [comment]
Hi @nishadotcom 
here is a simple example how you could use the min max options to simulate the zoom behavior: http://plnkr.co/edit/KFkzukFYiUClu4FZc6iH?p=preview
Best,
Christoph

**Comment by nishadotcom** [comment]
Hi @chaosmail,

Great @chaosmail. But we miss the parent zoom functions. Isn't it????

I like to know about you personally. If you don't mind could you please share your contact.

My contacts,
Skype : benedictnishanth
Yahoo : nisha.com126@yahoo.com

**Comment by chaosmail** [comment]
Hi @nishadotcom 
this is of course just a starting point and needs to be developed a little bit further to do exactly what you want for your case. If it is helpful for others, I would prefer to have all discussions in public on Github. This helps others who want to solve the same problem as you.

If you have a particular question related with n3-charts, you for sure can ask me and I will try to figure out a solution. But unfortunately I cannot do all the work for you ;)

Best,
Christoph

**Comment by nishadotcom** [comment]
:+1:

**Comment by nishadotcom** [comment]
Could you please tell me explain the below code???

$scope.$watch('zoom', function(){
    if ($scope.options.axes) {
      $scope.options.axes.x.min = new Date(minX.getTime() + parseFloat($scope.zoom) * (maxX.getTime() - minX.getTime()) * 0.5);
      $scope.options.axes.x.max = new Date(maxX.getTime() - parseFloat($scope.zoom) * (maxX.getTime() - minX.getTime()) * 0.5);
    }
  });

**Comment by chaosmail** [comment]
Hi @nishadotcom 

`minX.getTime()` ... we get the timestamp from the Date object `minX`
`(maxX.getTime() - minX.getTime())*0.5` .. the interval from min to max in milliseconds, we use this as our zoom range; we only take half, because we add it to the min and subtract it from the max
`parseFloat($scope.zoom)` ... a factor from [0, 1] to determine the zooming level.

 Best,
Christoph
