### ISSUE TITLE
Areas and Lines deviate in area mode

### ISSUE THREAD

**Issue by CCJordan** [n3-charts/line-chart#360]
I'm trying to plot network data statistics and noticed horrible deviations in area and line plot of data plotted as area.
![bildschirmfoto 2015-10-29 um 22 10 36](https://cloud.githubusercontent.com/assets/2790276/10832157/eff88458-7e89-11e5-9988-fd748a321125.png)

My dataset looks like this:
| x | in | out |
|---|----|------|
| 0 |  0 |   1 |
| 1 |  2 |   1 |
| 2 |  6 |   1 |
| 3 |  2 |   1 |

The rest of my code is pretty much your example code: http://codepen.io/anon/pen/meKVQL

**Comment by lorem--ipsum** [comment]
Hi and thanks for the interest. Is there any particular reason you're using strings to plot your data ?
