### ISSUE TITLE
Where could I find the n3-chart documentation?

### ISSUE THREAD

**Issue by nishadotcom** [n3-charts/line-chart#364]
Where could I find n3-chart documentation. It would be more feasible for new users.

**Comment by chaosmail** [comment]
Hi @nishadotcom 
you can take a look at our Wiki: https://github.com/n3-charts/line-chart/wiki
you can also find examples on our website: http://n3-charts.github.io/line-chart/
Let me know if you need any further help!
Best,
Christoph

**Comment by nishadotcom** [comment]
Thanks Christoph

**Comment by nishadotcom** [comment]
Hai Christoph,

I have x-axis as date.
I need to set the interval (5). How to do???? Could you please guide me?????

**Comment by chaosmail** [comment]
You can use the `ticksInterval` option, here is an example: http://plnkr.co/edit/hWBoETLpgDJjgtGbiC8R?p=preview

**Comment by nishadotcom** [comment]
Yes Christoph, I got it. It works!!!!

**Comment by nishadotcom** [comment]
Hai Christoph!

Could you please suggest any idea / your guidance for the following???? 
https://github.com/n3-charts/line-chart/issues/358
