### ISSUE TITLE
Load Limit Data

### ISSUE THREAD

**Issue by nishadotcom** [n3-charts/line-chart#365]
How to load limit data from large????

Ex:
Here I have set of data(6)
$scope.data =  [
      {x: 1, yAxisValue: 440},
      {x: 2, yAxisValue: 150},
      {x: 3, yAxisValue: 440},
      {x: 4, yAxisValue: 150},
      {x: 5, yAxisValue: 440},
      {x: 6, yAxisValue: 440}
]

But I like to **display only 3 data** on chart and others when I zoom.

**Possible????**
Please suggest.

Regards,
nishadotcom

**Comment by chaosmail** [comment]
Hi @nishadotcom 
you can use the `min` and `max` options on the series to achieve this!
Best,
Christoph

**Comment by nishadotcom** [comment]
Hi chaosmail,
min and max for axis value.
isn't it?????

**Comment by nishadotcom** [comment]
Hi Christoph,
For Example,
$scope.data = [
{x: 1, yAxisValue: 440},
{x: 2, yAxisValue: 150},
{x: 3, yAxisValue: 440},
{x: 4, yAxisValue: 150},
{x: 5, yAxisValue: 440},
{x: 6, yAxisValue: 440}, ....... till 30
]
I have 1 month(1 to 30) data for chart.

but I like to display only few(may be 10) on chart when page loads.

can we do it????

Regards,
nishadotcom

**Comment by chaosmail** [comment]
Yes, you can use `Date` values for the `min` and `max` options on `$scope.options.axes.x`.
