### ISSUE TITLE
Is there an option somwhere to create grouped tooltip?

### ISSUE THREAD

**Issue by pitieu** [n3-charts/line-chart#366]
Here's an image i saw from issue #362 
https://cloud.githubusercontent.com/assets/1224709/10915871/fdd0961a-8258-11e5-92db-8946b3997128.png

How can i group all values together in one tooltip ? Is there an option to do this?

**Comment by chaosmail** [comment]
Hi @pitieu 
this is version 2 of n3-line-charts which is currently in development and on the `dev` channel. you can already try the beta version; more infos here: http://n3-charts.github.io/line-chart/v2
Best,
Christoph

**Comment by pitieu** [comment]
ok Thx :+1:
