### ISSUE TITLE
How to display the value on or above a bar?

### ISSUE THREAD

**Issue by shlomogoldstein** [n3-charts/line-chart#376]
I want to display the value of a bar permanently on the bar itself or on top. How can I achieve this? It should not interfere with the tool tip functionality. I am using a stacked bar, so this should work for each bar part.

**Comment by chaosmail** [comment]
Hi @shlomogoldstein 
This is currently not possible due to some restrictions with the tooltips. However, we will release version 2 soon, where sth like this is very easy to implement. You can take a look at the `dev` branch already today, if you are keen to implement it.
Best,
Christoph

**Comment by shlomogoldstein** [comment]
Then is there a possibility to permanently display the tooltip? If so I can use the original tooltip as a label on each bar. Using the on-hover I could create another tooltip to display other data. Is it possible?

**Comment by michalmikolajczyk** [comment]
+1

**Comment by shlomogoldstein** [comment]
I switched to chartist. It is easy to integrate that feature there.
