### ISSUE TITLE
Can not access row data in nested objects

### ISSUE THREAD

**Issue by KIC** [n3-charts/line-chart#381]
I have a data like this: 

{"x":1161558000000,"_1567197553":{"r":0.0009164055359707446,"np":3,"R":1.0009164055359707,"s":0,"e":null},"_730773400":{"r":0.0020962991977484524,"np":3,"R":1.0020962991977485,"s":0,"e":null},"_985498009":{"r":0.006747324336900951,"np":1,"R":1.006747324336901,"s":0,"e":null}}

And I want to draw a series like so:

options.series[0] = {"y":"_1567197553.R","type":"line","visible":true,"label":"super chart","axis":"y","striped":false,"thickness":"1px","drawDots":false,"color":"#1f77b4","id":"series_0"}

Then the chart just stays empty.

**Comment by BinaryWasteland** [comment]
Hey @KIC,

I had the same issue here - https://github.com/n3-charts/line-chart/issues/262 - and needed to use a <code>map</code> to extract the data to the root of the object. I believe V2 can handle nested objects but @chaosmail would be able to confirm that.

- BinaryWasteland

**Comment by chaosmail** [comment]
Exactly, you would have to map your data to get a flat array. V2 Allows a more flexible structure for multiple datasets; however, also in V2 the datasets need to be flat.
Best,
Christoph

**Comment by KIC** [comment]
thx for the quick respond. 

flattening out is one option. I send loads of data so nested objects saves me some bytes. but the flattening process costs some cpu. I am nur sure if I should flatten the data serverside - but then I have more bytes to send over wire ... on the other hand maybe you can jsut point me to the piece of code getting the y value. a simple eval there should do the trick.

**Comment by lorem--ipsum** [comment]
It's not that simple: data is accessed from various places in the framework. You're obviously free to make any modifications you want on your version of the lib, but I don't recommend it, for several reasons : 
 - very little chance to see this merged (we don't support hierarchical datasets, and it's not likely to happen anytime soon)
 - what you don't pay in preprocessing, you pay in rendering, for large datasets. At least, the preprocessing cost is under control and measurable.

How big are your standards datasets ?

**Comment by lorem--ipsum** [comment]
Hey, we're closing this because it's been a while and we're trying to avoid zombie issues. If the problem persists, please open a new issue (and don't forget, your issue is much more likely to be fixed if you provide a working [CodePen](http://n3-charts.github.io/line-chart/#/examples) : easier for us, faster for you !).

Thanks again for helping us making n3-charts awesome.

--
_Sébastien & Christoph_
