### ISSUE TITLE
Can we change X - Y Axis fonts?

### ISSUE THREAD

**Issue by megharajdeepak** [n3-charts/line-chart#389]
Was wondering if there is a way to change axes fonts.
I tried:
linechart
		{
			font-family: Tahoma;
		}
But nothing changed. Am I missing something?

**Comment by chaosmail** [comment]
Hi @megharajdeepak 
take a look at this example: http://plnkr.co/edit/qVKKnbywFAELLh2QWzem?p=preview
Best,
Christoph

**Comment by megharajdeepak** [comment]
Thanks Christoph.
I tried this:
 <style>
    .chart *[style], .chart *[font-family] {
      font-family: 'Droid Sans', sans-serif !important;
      font-size: 1.5em;
      -webkit-font-smoothing: antialiased;
    }
  </style>

Tooltip isn't showing up. However, if i change font-size to pixels instead of ems, it works. Isn't em supported? I tried that in Chrome 47.
