### ISSUE TITLE
Hiding the `y` axis

### ISSUE THREAD

**Issue by michalmikolajczyk** [n3-charts/line-chart#390]
Is it possible to hide the `y` axis, while still showing the series bound to it?
It would be a nice option, especially with the `column` type. Users could still read values from the tooltip.

**Comment by adonespitogo** [comment]
My workaround is using css.
```css
g.axis.y-axis {display: none}
``

**Comment by adonespitogo** [comment]
I found a better work around. Just add `margin: {left: 0}` in your config
