### ISSUE TITLE
Chart is not resize when open Chrome Developer Tools

### ISSUE THREAD

**Issue by pacozaa** [n3-charts/line-chart#391]
## Line Chart doesn't detect fast resize
* It will show the oversize graph and too tiny size graph when I resize fast using my mouse. I have to slow resize again to adjust the graph size correctly.
* "Fast" means that I move my mouse to resize web browser windows as fast as normal people can.

**Comment by lorem--ipsum** [comment]
Soooooo what's the question ? :)

**Comment by pacozaa** [comment]
How to fix this problem? Chart will over size or under size from their parents when I resize fast.
How to fix it?

**Comment by chaosmail** [comment]
Hi @pacozaa 
is this still a problem? have you tried our latest version v2 (installation guide can be found here http://n3-charts.github.io/line-chart/)?

Best,
Christoph

**Comment by pacozaa** [comment]
@chaosmail  Thank you,sir. I have try to use v2(with angular,meteor) but I face another problem. I will open new issue asap.
