### ISSUE TITLE
Axis labels overlay

### ISSUE THREAD

**Issue by Maikor** [n3-charts/line-chart#392]
Hello, I have few series and bug appears in Chrome with AXIS names.
![alt text](http://s8.postimg.org/cwzxf67k5/Capture.png "Before")
After one of axis clicked below graphs, their position become normal.
![alt text](http://s23.postimg.org/rsspkm4dn/Capture2.png "after click")

**Comment by lorem--ipsum** [comment]
Hm. Have you tried v2 ?

**Comment by Maikor** [comment]
Not yet:)

**Comment by chaosmail** [comment]
Hi @Maikor 
this should work great in the latest version. Please let me know if you have any troubles updating - you can use also the information provided on http://n3-charts.github.io/line-chart/.
Best,
Christoph
