### ISSUE TITLE
Brushing (enhancement request)

### ISSUE THREAD

**Issue by yanakad** [n3-charts/line-chart#399]
I see a few questions on Gitter around this with a "coming soon" reply so I thought I'd make an official request. Can we please be able to do this:

http://bl.ocks.org/mbostock/1667367

Any swag on timeline would be awesome too

**Comment by chaosmail** [comment]
Swag you say? we made stickers some time ago. Drop me a message if you are in europe to get some ;) and yes, we are planning to integrate brushing soon.

**Comment by lorem--ipsum** [comment]
Closing it since zooming and panning are out.
