### ISSUE TITLE
Version 2 zoom

### ISSUE THREAD

**Issue by xshaka** [n3-charts/line-chart#403]
Is it zooming the chats available in version 2? Either I cannot find a way to configure the zoom for my axes or, the zoom is enabled with the 'pan' configuration but it doesn't work for me.

**Comment by chaosmail** [comment]
Hi @xshaka 

thanks for raising this question. @lorem--ipsum was the guy implementing most of this, so I pass this question to me.

@lorem--ipsum what is the status about zooming and panning?

I will try to put a little demo together in case it is working fine.

Best,
Christoph

**Comment by xshaka** [comment]
@lorem--ipsum, @chaosmail, there is also another issue, related with the zooming functionality: I have been playing around with some d3-related charting libs, and they all have a particular issue, there is no way to limit the panning to the current data set limits. For example, say I have a xAxis where all values are in the range [1, 200], when panning/zooming, I would like to stay within that range. I have found that root cause is the fact that d3 doesn't provide a way to do that, even when there are plenty of users asking for that feature. Some time ago, it appears that some d3 contributor added a commit related to this, as you can see here: https://github.com/mbostock/d3/pull/2019, but that hasn't been included in any final released and it certainly doesn't work on current d3 version (3.5.12, I have tried). Is there something you can do about this?

**Comment by lorem--ipsum** [comment]
The status about panning and zooming is... I'd say 50% done. So basically panning is working but not well tested, and zooming should be working but I haven't even checked that... (too much work on the other side :( )

**Comment by lorem--ipsum** [comment]
Closing this as zooming and panning are out.

**Comment by naduda** [comment]
Can You create a demo with zooming and panning?
