### ISSUE TITLE
redraw after data update

### ISSUE THREAD

**Issue by mhogeweg** [n3-charts/line-chart#405]
based on some user choices the data in my chart changes. the data object that the chart is bound to is updated in code, but the chart doesn't seem to change.

```
<linechart data="data" options="options" height="700" ></linechart>		
```

Not seeing any error messages, just no change in the chart. any thoughts?

**Comment by chaosmail** [comment]
HI @mhogeweg 
do you use v1 or the new version v2? Would it be possible to reproduce the error in a Codepen (maybe start from this example: http://codepen.io/chaosmail/pen/xZgPmp)?

Where does the user data change? Outside of Angular code maybe? Could you put $scope.$apply() behind the change and see if it is still the same?

Best,
Christoph

**Comment by mhogeweg** [comment]
sproing! that did the trick! thanks

**Comment by chaosmail** [comment]
Great, let me know if you need any more help. I am putting together a demo for the ´tooltipHook´
