### ISSUE TITLE
How to create stepped line chart?

### ISSUE THREAD

**Issue by samwzm** [n3-charts/line-chart#408]
Hi, there,

I am wondering if n3-charts support stepped line chart? something like below:

http://jsfiddle.net/hrabinowitz/abJLf/22/

Although above is based on d3, ne-charts is based on d3, so I think it should support. however, I can't find any document. I also tried here and there without luck. especially I tried lineMode: "step-after" without success.

Any help or sample would be greatly appreciated!
Sam

**Comment by chaosmail** [comment]
Hi @samwzm 
The `interpolation` option for each series is your friend, try `step`, `step-before` or `step-after`. Here is a demo http://codepen.io/chaosmail/pen/OMvMRM

Best,
Christoph

**Comment by samwzm** [comment]
Thank you very much for the prompt help, Christoph! it works!

by the way, are there more detailed documents about n3-charts, especially for the beginner (without d3 experience)? the doc in the website is clear, but missing lots of details. 

thanks again,
Sam

**Comment by chaosmail** [comment]
thanks for the kind feedback. Yeah, we know that the docs are lacking a lot of information, and it's on our todo list to improve them. If you want to help us, feel free to add something (maybe about the interpolation) to the docs (https://github.com/n3-charts/line-chart/blob/master/docs/usage.md) and submit a PR. We are always happy about community support :)
