### ISSUE TITLE
v2 zoom and stepped line chart

### ISSUE THREAD

**Issue by samwzm** [n3-charts/line-chart#411]
Hi, there,

I need zoom and stepped line functions. However, it seems zoom function only works in n3charts version 1, and stepped line chart only works in n3charts version 2.

By checking the issues, seems like the main issue about zoom function in version2 is related with d3. If that's the case, I am guessing it would be easier to use stepped line chart in version1. Could anyone help me how to do that?

Thanks!
Sam

**Comment by samwzm** [comment]
really appreciate any help!

**Comment by chaosmail** [comment]
Hi @samwzm 
In v1 stepped functions work perfectly fine, you can take a look at this example: http://codepen.io/chaosmail/pen/MKXOoM

However, the option is called `lineMode` and works only for all series.

And zooming is on the way for v2!

Best,
Christoph

**Comment by samwzm** [comment]
Thanks, Christoph! it works like a charm.
