### ISSUE TITLE
How to combine two different series types in one chart?

### ISSUE THREAD

**Issue by samwzm** [n3-charts/line-chart#413]
Hi, there,

I want to combine line series and stepped line series in a single chart. both series will share the same x axis (as time), but will have their own y axis. Is that possible in n3-charts version 1? (the reason why I want to use version 1 is because of the zoom function)

I know there is an example for two axes in one chart (as in below URL), however, in that example, both series have the same type/mode. My question is that the two series are not the same type/mode.

http://n3-charts.github.io/line-chart/v1/#/examples

If possible, could anyone share an example?

Thanks again!
Sam

**Comment by samwzm** [comment]
anyone could help :-)

Sam

**Comment by lorem--ipsum** [comment]
I don't think it's possible in v1 due to the series sharing the same interpolation mode...

**Comment by samwzm** [comment]
I see, thanks for the update, Iorem--ipsum!

by the way, is that possible to do it in V2? if possible, could you please share a simple example?

I know the zoom function is on the way in V2. Is there any rough timeline for that :-)

thanks again,
Sam

**Comment by lorem--ipsum** [comment]
So I think what you're trying to achieve is exactly what's shown in the example "Interpolation" of the examples page (http://n3-charts.github.io/line-chart/#/examples). About the zoom, i'm working on it right now and it should be out by the end of the week.

**Comment by samwzm** [comment]
excellent, can't wait for the zoom function in V2!

by the way, where should I check to get the update? Or is there any notification that I can subscribe to get the latest update.

thanks again

**Comment by lorem--ipsum** [comment]
Hmmm we don't have anything right now for that, but I think if you star the project you receive notifications about it or something like that...

**Comment by samwzm** [comment]
based on my searching, star won't receive notification. (I have starred your project because it's very useful). I have watching all the issues, so could you please make announcement through here, so all the people who are watching will get notification.

**Comment by lorem--ipsum** [comment]
I guess we could have some sort of a "sticky" issue that people would subscribe at, and where we'd put the announcement. A redneck blog, in a nutshell ^^

**Comment by lorem--ipsum** [comment]
#419 !
