### ISSUE TITLE
Missing migration guide

### ISSUE THREAD

**Issue by ulejon** [n3-charts/line-chart#414]
Hi

Is there some kind of migration guide for upgrading from v1 to v2?

**Comment by lorem--ipsum** [comment]
That's a very good idea, there's not currently something that addresses migration. We'll take a look at that.

**Comment by ulejon** [comment]
Perfect!

I haven't tried the migration myself, but a team member told me that v2 is not backwards compatible with v1?

**Comment by lorem--ipsum** [comment]
Yeah, that's true. There are differences in the data format (not major ones though) and the options are different too. You guys are using n3-charts for something fun ?

**Comment by ulejon** [comment]
Alright!

We are using it to show trends in measurements. Can't really say more than that :)

**Comment by lorem--ipsum** [comment]
Coolio, I'm always wondering what people use n3-charts for :)
