### ISSUE TITLE
CSS-class-name conflicts with Bootstraps v3.3.5

### ISSUE THREAD

**Issue by ejuanis** [n3-charts/line-chart#420]
I'm upgrading from v1(1.1.12) to v2(2.0.8), however, the legends are not displayed correctly due to css-class-name conflict with Bootstraps v3.3.5. Details as below:

## .label
**LineChart 2.0.8** _line 23_
```
.chart-legend .item > .label {
  height: 16px;
  line-height: 17px; }
```

**Bootstrap 3.3.5** _line 4854_
```
.label {
  display: inline;
  padding: .2em .6em .3em;
  font-size: 75%;
  font-weight: bold;
  line-height: 1;
  color: #ffffff;
  text-align: center;
  white-space: nowrap;
  vertical-align: baseline;
  border-radius: .25em;
}
```

## .hidden
**LineChart 2.0.8** _line 33_
```
.chart-legend .item.hidden {
  opacity: 0.4; }
```
  
**Bootstrap 3.3.5** _line 6547_
```
.hidden {
  display: none !important;
}
```

@lorem--ipsum, any recommendation how to resolve this issue?

**Comment by lorem--ipsum** [comment]
Well, it looks like the conflict comes from Bootstrap... We can't play this little game of making sure our CSS rules have precedence over other frameworks' rules, so I suggest you use another UI framework (one that doesn't assume it's the only one in the entire world :D)

Sorry ¯\_(ツ)_/¯

**Comment by magnusart** [comment]
Well to be fair Bootstrap is not exactly an esoteric library. I find it a bit concerning that you don't care at all about mitigating collisions. Would it be an abomination to add a `n3`-prefix to the css classes in question?

Why N3 and not Bootstrap you ask? 
Bootstrap has been around for a good while before N3-charts. In the end N3-charts will always loose if the choice is between it and Bootstrap. We could write our own charting library wrapper several times over before we'd be done replacing Bootstrap. I suspect other users of Bootstrap would feel the same.

**Comment by chaosmail** [comment]
Hi @magnusart
Thanks for reporting this issue! I think @lorem--ipsum was a little sarcastic here. In fact, it is a high priority to provide compatibility to the major JS libs that are out there and I could imagine he is already working on a fix. You solution sounds very good,  maybe a n3-* prefix is both short and elegant.
Best,
Christoph

**Comment by lorem--ipsum** [comment]
Yeah I was being sarcastic, but the point is : a

**Comment by lorem--ipsum** [comment]
Yeah I was being sarcastic, but the point is : adding a prefix wouldn't solve the problem, which is that Bootstrapp's selector target classes the same way that a shotgun would target a mosquito : efficient, but with some collateral damages. The only way this can be solved (after a three minutes investigation, however) is to change the conflicting class names : `label` would become `legend-label`, for instance.

**Comment by magnusart** [comment]
I hope I'm not conveying that I think that Bootstrap is not at fault here. Far from it. I do sympathize with your view in the sense that it's annoying that they took shortcuts in order to have their CSS work at the expense of others. Your sarcasm was not lost on me. I just wanted to make an argument that regardless of things being unfair, the pragmatic way forward (from our perspective) is to adapt in the N3 library. 

If you do not disagree we can do this change and submit a pull request adding `legend` prefix in front to `label` and `hidden` classes. I imagine it should be quite a small taks.
