### ISSUE TITLE
How to combine two different series types in one chart in V2

### ISSUE THREAD

**Issue by samwzm** [n3-charts/line-chart#421]
Hi, there,

in V2, I want to combine two different series types. I tried below code without success. could anyone share an example? by the way, the two y axis have different value (for example, one is to show price, and another is to show position).

thanks!

below is my controller:

                    $scope.combinoptions = {
                        	
                            series: [
                                {
                                    axis: "y",
                                    dataset: "dataset1",
                                    key: "price",
                                    label: "price series",
                                    color: "#1f77b4",
                                    type: ['line', 'dot'],
                                    id: 'mySeries0',
                                 },
                                {
                                    axis: "y",
                                    dataset: "dataset1",
                                    key: "position",
                                    label: "position series",
                                    color: "#d62728",
                                    type: ['line', 'dot'],
                                    id: 'mySeries1',
                                    interpolation: {mode: 'step-after'}
                                }
                                
                            ],
                            margin: {
                            	top: 40,
                                bottom: 40,
                                right: 80
                              },
                              hideOverflow: true,

                            axes: {x: {key: 'time', zoomable: true}}
                            
                        };

**Comment by samwzm** [comment]
anyone can help?

thanks!

**Comment by chaosmail** [comment]
Hi @samwzm 
what do you need exactly? You are saying `different series`.. do you mean different types (use ` type: ['line', 'dot']` option) or different interpolations (use `interpolation: {mode: 'step-after'}` option).
Best,
Christoph

**Comment by samwzm** [comment]
Hi, Christoph,

what I want is to have same type ['line','dot'], but different interpolations (one is simple line, another is step line by using interpolation: {mode: 'step-after'}).

thanks,
Sam

**Comment by chaosmail** [comment]
You can of course just use different interpolations per series, like in this example http://codepen.io/chaosmail/pen/ZQMjdN

**Comment by samwzm** [comment]
Thanks, Christoph! however, the above example shares the same y value for all the series. in my case, it won't work, because the values of the two series are very different. If the two series share the same y axis value, then one of the series is almost a line.

in fact, in version 1, I can do that perfectly by specifying  axis: "y" and axis: "y2" in corresponding series. by doing that, right y axis's value is different left y axis's value, and the two series display nicely.

however, I tried using axis: "y2" in version 2 without lucky. in a word, what's the corresponding approach in V2 as  axis: "y2" in V1?

please let me know if I didn't explain myself clearly.

thanks again,
Sam

**Comment by chaosmail** [comment]
Alright, I see your problem now. @lorem--ipsum I saw `x2` and `y2` in the code, any idea what is left to do to support it?

**Comment by lorem--ipsum** [comment]
Well implementing this probably needs a couple of days, I'd say.

**Comment by chaosmail** [comment]
Alright, thanks for the update. So @samwzm we don't support multiple y axis yet, however we have it on our list of tasks. Btw. zoom just arrived in the latest version today ;)

**Comment by samwzm** [comment]
Thanks for the update, Christoph. I have got email about zoom function, well done!! I will give it a try tomorrow.

By the way, is that possible to make multiple y axis higher priority? I have a demo early next week, and have to use multiple y axis. I know V1 supports multiple y axis, however, V2 chart is much attractive than V1, that's why I want to use V2 to do the demo.

thanks again!

**Comment by lorem--ipsum** [comment]
Woops, looks like your message slipped through, sorry. The project's is mostly worked on  when our respective works allow it (I wish I could get paid to work on n3-charts though ^^), so priorities don't really affect the project's development...

**Comment by pcs9124** [comment]
lorem-ipsum - great upgrade, except for this lack of y2 feature.
If you are looking for up votes to prioritize, I will vote for atleast y2. 
I am holding back switching to v2 just because of this feature.

**Comment by lorem--ipsum** [comment]
Please check out 2.0.16 !
