### ISSUE TITLE
Is that possible to add vertical label along y axis?

### ISSUE THREAD

**Issue by samwzm** [n3-charts/line-chart#422]
for a chart containing two series, since those two y axis are different data, is that possible to add a vertical label along the y axis? for example, on the left y axis, the label is "Price", on the right y axis, the label is "Position"?

**Comment by lorem--ipsum** [comment]
I'm assuming you're talking about v1, right ?

**Comment by samwzm** [comment]
no, I am talking about v2.

I know I can do it through css. Just out of curiosity, if n3-charts already provides this feature, then I can directly use :-)

**Comment by chaosmail** [comment]
Nope, use CSS transform. Let me know if you need help on this
