### ISSUE TITLE
about x2 and y2 issue in V2

### ISSUE THREAD

**Issue by samwzm** [n3-charts/line-chart#428]
Hi, there,

is there any rough timeline to fix this issue in V2? I would appreciate if anyone could give me update, because I need to make the decision which chart tool to use.

thanks!
Sam

**Comment by lorem--ipsum** [comment]
Well, that's not an easy task, but I'm seeing this happening in a month or two, I guess.

**Comment by samwzm** [comment]
any update about this issue?

thanks!

**Comment by lorem--ipsum** [comment]
Hey, check out 2.0.16 !
