### ISSUE TITLE
Negative values break chart entirely

### ISSUE THREAD

**Issue by Seikilos** [n3-charts/line-chart#430]
I've played around with this fine library, however I noticed something weird. When using negative values the rendering does not fit the entire data into the chart.
Here is the Plnkr for it: http://plnkr.co/edit/7dRqe3JPQg86FD0hVWbc?p=preview
Observed on latest Firefox, Chrome, IE 11 and Edge
Both large and small values are off the chart and the data is supposed to be continuous. You can see values above 100 in the first part and negative values on the right via the tooltip.

**Comment by lorem--ipsum** [comment]
That's because your `val_0` are passed as strings : http://plnkr.co/edit/KcTQjP3RepXBh8gUpCPw?p=preview

**Comment by Seikilos** [comment]
I can confirm this. But why is the algorithm spacing for a range of [0..100] then? The default one looks like it scales the Y axis to [0..1] per default and infer a size of [0..100] from my string values? Should n3 probably warn about that?

**Comment by lorem--ipsum** [comment]
Hmmmm it could, yeah, but we try to focus on performance, and checking data against all possible use cases can be lead to performance issues (and we have enough of them already ^^). About why n3 is behaving like this for string data, I have no idea what can cause this result. that'd be interesting to investigate.
