### ISSUE TITLE
Disable animation in V2

### ISSUE THREAD

**Issue by adonespitogo** [n3-charts/line-chart#434]
Is it possible to disable animation?

**Comment by lorem--ipsum** [comment]
Hmm nope. Any specific use case in mind ?

**Comment by adonespitogo** [comment]
My use case is I have a customized zoom and scroll bar. I am moving and manipulating the data in the chart manually according to zoom and scrollbar position. The animation makes the transition of the chart laggy and weird. I found the a work around by modifying the source `Transition.defaultDuration = 250` and changed the value to `0`. Please let me know if there is a better approach in doing custom zoom/scrollbar.

**Comment by lorem--ipsum** [comment]
We weren't exactly thinking of this as an exposed property, but if it works, I guess you can use it ! :)
