### ISSUE TITLE
Top label on y-axis is cut-off

### ISSUE THREAD

**Issue by pyotrrtichie** [n3-charts/line-chart#436]
Hi there,

I'm having a style issue where the top label is cut in half by what appears to be 

`<defs><clipPath` id="clipping-path"><rect transform="translate(0, 0)" height="280" width="1490" `id="clipping-rect"></rect></clipPath></defs>`

But then if I delete this node the height of the chart container still does not allow enough room.

Any help, would be much appreciated.

Pyotr

**Comment by lorem--ipsum** [comment]
Use the `margin` option to add extra space on top of the chart.

**Comment by pyotrrtichie** [comment]
Thanks for the response, I've tried increasing this but it has absolutely no effect - any idea why this might be?
I would like to attach a screen grab but basically it is only an issue in firefox and chrome; internet explorer shows the labels correctly. Don't suppose this is something that anyone else has found?

**Comment by lorem--ipsum** [comment]
Can you post an example (in CodePen for instance) so we can reproduce the bug and see what's going on please ? :-)

**Comment by chaosmail** [comment]
Duplicate of #474 Please check the workaround there until we add an option to disable clipping.
