### ISSUE TITLE
Unexpected resizing

### ISSUE THREAD

**Issue by allyhume** [n3-charts/line-chart#439]
I am experiencing some unexpected resize of my charts. Is this a bug or am I failing to understand something?

Starting from the full example at: http://n3-charts.github.io/line-chart/#/docs whenever I resize the width of my browser window the chart grows a little in height each time.

Also if I add a simple number input element:

    <body ng-controller='MyChartCtrl'>
      <input type="number" id="myNumber" ng-model='myNumber'>
      <div class="my-chart">
        <linechart data="data" options="options"></linechart>
    </div>

Now every time I click on the arrows to increase or decrease the number in that input box then the chart grows in height.

Is there a way to prevent this resizing of the chart?

I'm using n3-charts 2.0.14 and angularjs 1.5.0.

**Comment by lorem--ipsum** [comment]
Yeah that's because you have to give an explicit height to the chart's container.
