### ISSUE TITLE
Tooltip overlaps tooltip

### ISSUE THREAD

**Issue by kandarpbhesaniya** [n3-charts/line-chart#443]
Is there a solution for this?
![123](https://cloud.githubusercontent.com/assets/11554884/13372238/4609c00a-dd62-11e5-8923-704224bd7e06.png)

**Comment by lorem--ipsum** [comment]
Yep, use v2 :-)

**Comment by kandarpbhesaniya** [comment]
thanks...totally forget..to update :D
