### ISSUE TITLE
How do you get click callback working in v2

### ISSUE THREAD

**Issue by pcs9124** [n3-charts/line-chart#445]
In v1 there was click and onclick in scope. But with v2, neither work.
Documentation is quiet as well.

Would be nice if a demo sample can be documented.

**Comment by lorem--ipsum** [comment]
Congratulations ! You've requested a feature that's not yet implemented, and as a first-time requester you get to tell us how you'd like it to behave ! :-) If your request is not too complicated, I'll probably take care of it this week.

**Comment by pcs9124** [comment]
I obviously want the data point - just the absicca would be fine as well.
I am using multiple charts in a page so reference to which chart would be important.
Could get fancy like knowing if the click was on the axes or legend.

**Comment by lorem--ipsum** [comment]
Hmm okay so I think it's gonna be something like the data row, and the series. The event will occur on dot or column click, obviously, so no need for click origin.

**Comment by pcs9124** [comment]
I have multiple graphs in a ng-repeat, so if I get context of the graph that would be useful.

**Comment by lorem--ipsum** [comment]
Hmm the chart shouldn't be aware of what's going on externally. You can add the `$index` parameter to anything inside of an `ng-repeat` to identify the chart.

**Comment by pcs9124** [comment]
Sure - I was only looking for a id. Thanks
