### ISSUE TITLE
does not show first column of series...how to

### ISSUE THREAD

**Issue by kandarpbhesaniya** [n3-charts/line-chart#446]
![untitled1](https://cloud.githubusercontent.com/assets/11554884/13394494/c6e86b9c-df0e-11e5-8642-e5335042e348.png)

first column of Prior Year series does not show January column.....what am i doing wrong?

**Comment by lorem--ipsum** [comment]
could you set up a codepen with your example so w can take a look at it please ?

**Comment by kandarpbhesaniya** [comment]
http://codepen.io/anon/pen/RaNZXL

**Comment by lorem--ipsum** [comment]
Okay so that's a bit of a stretch but you can add an empty first data point, and tell the chart not to render it using the `defined` attribute. See example : http://codepen.io/anon/pen/jqExPa

**Comment by kandarpbhesaniya** [comment]
yes i did this method...but i thought if chart provides any options.....thanks @lorem--ipsum

**Comment by kandarpbhesaniya** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11554884/13485295/5167bf7e-e12c-11e5-8b4c-1eb45e21b948.png)

how to remove highlighted Y axes(right side) from chart?
