### ISSUE TITLE
Nanosecond data

### ISSUE THREAD

**Issue by samwzm** [n3-charts/line-chart#453]
Hi, there,

can n3-charts handle nanosecond data (x-axie)?

also, for the X axie label (time), I don't need nanosecond accuracy, second is good enough. could anyone give me an example of this?

many thanks,
Sam

**Comment by lorem--ipsum** [comment]
It's perfectly doable, but not with the native date/time axis. You'll have to use a regular numerical axis, and use a custom formatter for the x-axis.

**Comment by samwzm** [comment]
Thanks, Lorem!

Is there any sample, or documentation that I can refer to?

**Comment by samwzm** [comment]
another comment, although Java 8 Date can provide nanosecond, however, previous of Java 8, the Date can only provide millisecond. also, how about javascript date, I believe it can only provide millisecond.

although java timestamp can provide nanosecond, I don't know if n3chart/d3 can accept timestamp, instead of date object.

**Comment by samwzm** [comment]
there is a work around solution. I can use number in x-axis, for example, 93015123456 represents 9:30:15:123456 (nanosecond is 123456). My question is that how I can format the x-axis label, instead of  displaying as "93015123456", displaying as "9:30:15:123456" (which looks like time format). 

Could anyone give me an example if it possible?

many thx!
Sam

**Comment by chaosmail** [comment]
Hi @samwzm 
you can use a custom tick function (see tickFormat in the docs) to achieve this for the axis - and a tooltip hook for modifying the tooltip (here is an example http://codepen.io/chaosmail/pen/xZgPmp). You need some math - to extract the hours, minutes, seconds and nanoseconds from the timestamp - but this should be doable.
Best,
Christoph

**Comment by samwzm** [comment]
thanks for the help! this has been done, although there is an issue about how to control automatically generated x-axis labels. I have created another ticket for the issue and will close this one.
