### ISSUE TITLE
Zooming Issue in V2

### ISSUE THREAD

**Issue by samwzm** [n3-charts/line-chart#458]
Hi, there,

I found a zooming issue in v2. when I keep zooming in, eventually the lines are disappeared, although there is data point in it (I can find it when I use mouse cross the area).

FYI, I use y2 axis, and two different line types in the same chart (one series is line, another is interpolation: {mode: 'step-after'} ) .

Thanks!
Sam

**Comment by samwzm** [comment]
anyone could take a look?

thanks,
Sam

**Comment by chaosmail** [comment]
Could you provide a Codepen please?
