### ISSUE TITLE
ticks display question in V2

### ISSUE THREAD

**Issue by samwzm** [n3-charts/line-chart#460]
Hi, there,

I don't want to use auto tick feature, so that I provide the ticks data, which is huge (more than 10,000). by default, the n3 charts will display all the ticks, which makes block of dark areas (unless zoom in). 

if I didn't provide my own tick data, n3 charts will automatically display ticks nicely. for example, if I zoom in, more detailed ticks will display. however, I can't use this feature because some automatically generated ticks are not valid for my data.

My question is that if there is a way to auto display the ticks from the tick data I provided. 

by the way, I tried "ticksInterval", but it seems not work.

thanks,
Sam

**Comment by samwzm** [comment]
anyone could take a look?

thanks,
Sam

**Comment by chaosmail** [comment]
You could use the `on-domains-change` callback to update the `ticksInterval` option. Let me know if you need some help to implement this. A codepen would be great to start from
