### ISSUE TITLE
ticks - ticksRotate not work in V2

### ISSUE THREAD

**Issue by samwzm** [n3-charts/line-chart#461]
Hi, there,

it seems that ticksRotate does not work in V2. My code is based on this wiki page:
https://github.com/n3-charts/line-chart/wiki/Options

I don't know if the syntax changed, could anyone help with an example?

Thanks,
Sam

**Comment by samwzm** [comment]
anyone could take a look?

thanks,
Sam

**Comment by jfredsilva** [comment]
I'm also unable to rotate ticks

**Comment by chaosmail** [comment]
Yeah, `ticksRotate` is not yet implemented in v2 - and also the wiki is not up-to-date anymore (as we are having the docs now in the repo). If someone is wants to submit a PR this is highly welcome. The code is available in v1 and has to be ported to v2 - I will of course guide you
