### ISSUE TITLE
how to change chart size in V2

### ISSUE THREAD

**Issue by samwzm** [n3-charts/line-chart#463]
Hi,

I tried to increase the chart size (by default, the horizontal way works fine, it always automatically fill the whole screen. however, the vertical way is too small). I tried to add height:"800px" or height="100%" in the chart div. however, none of them works.

please advise.

thanks,
Sam

**Comment by jfredsilva** [comment]
You can change the height of the class chartbox-wrapper

**Comment by samwzm** [comment]
thanks, jfredsilva. however, I searched the css and can't find the class chartbox-wrapper. could you please share an example?

thanks,
Sam

**Comment by jfredsilva** [comment]
Sorry, in my case I named the linechart parent div with chartbox-wrapper.

<div class="chartbox-wrapper">
          <linechart class="chartbox" data="data" options="options"></linechart>
      </div>

**Comment by chaosmail** [comment]
Hi @samwzm 
does this work for you or do you still have issues?
Best,
Christoph

**Comment by xXanth0s** [comment]
Easily add this to your css file. You don't have to put your chart in a container

```
.chart-container, .chart {
  width:800px;
  height:330px;
}

```
