### ISSUE TITLE
How to set initial visibility of series to false

### ISSUE THREAD

**Issue by compsagnathus** [n3-charts/line-chart#464]
I have not had luck setting an initial visibility of a series to false when the chart is first displayed.  Any ideas what I am doing wrong?
```
 {
                axis: "y",
                visibility:false,
                dataset: "dataset00",
                key: "val_2",
                id: "val_2",
                label: graphDataSettings.seriesCollection[1],
                color: INV_COLOR_SET_CHARTS[2],
                type: [
                    "line",
                    "dot"
                ]
            },
```

**Comment by lorem--ipsum** [comment]
It's `visible`, not `visibility`.

**Comment by compsagnathus** [comment]
fantastic!  It works - thanks so much.  The documentation needs to be updated

![screen shot 2016-03-18 at 2 38 51 pm](https://cloud.githubusercontent.com/assets/17904268/13888349/682ecfee-ed17-11e5-88c5-fb72a7c86e6e.png)

**Comment by chaosmail** [comment]
Thanks for reporting this, the docs will automatically be generated with the next release and then the error will be fixed. However, we are working on a more robust setup to fix these things much faster.
