### ISSUE TITLE
Chart refresh issue "kind of"

### ISSUE THREAD

**Issue by miguelcastro67** [n3-charts/line-chart#465]
Hey there. For the most part, the chart is working very nicely in my solution. I have a series of data that can be viewed in three ways. Two them are "by-{something" type-views of simply pivoting the data and listing the results as actual text. The third is the line-chart view. I have this set up with three links that merely set a view variable and that variable is used in an ng-show of three <div> tags. All pretty standard stuff. When I click on my link for setting my variable to line chart mode so what was a text view now shows as the line chart instead, the legend shows and nothing else. Now here comes the fun part. To get the chart to show I can either click my "chart link" again, or resize the browser. In an attempt to find a hack, I attempted to resize the browser manually in the function called my three links (the one that simply was changing that view variable on which the ng-shows depend). It gets weirder. I can set the window's outerWidth (or height) to +1 and that fixes it but of course every time I click on the "show chart" link, the screen gets wider. So next I try to increment the width of the outerWidth, then immediately decrease it again and it brings the problem back. I've also tried to reset the binding to which the data is set to in line chart and no joy. I've also tried to programmatically "click" the link again and also nothing. When no chart shows, all it takes is a browser size adjustment to make it show so it's obviously a visual quirk. I also have a feature where I can press a button to make the size of the chart adjust. Currently the chart takes up the right-most 6-grid-columns of a bootstrap row (col-md-6) with a grid of data taking up the left most. My button simply hides the grid and changes the class of the chart's container to col-md-12 so it takes up the full width. When I try this, the chart, in it's current 6-column-width simply moves all the way to the left. But then again, simply touching the browser resize bar makes it complete its trip across all 12 grid-columns. I think these two visual quirks are related since they are both fixed with a simple browser resize, but obviously I can't count on that user-interaction as the solution. Any ideas?

**Comment by chaosmail** [comment]
Hi @miguelcastro67 
yeah, your case is one of the cases where the automatic dimensions of n3-charts wont work. This happens because the only resize event in a browser is triggered by the window element - and this is the only event we can listen to in order to automatically update the dimensions.

There are 2 options:
* set the width of the container manually (per CSS). 
* manually trigger a resize event when the chart appears (when the user clicks the link to show the chart)

Hope that helps, let me know if you have any further issues.

Best,
Christoph

**Comment by miguelcastro67** [comment]
So here's what's interesting. Doing a resize in code works, but only if the end result is truly a different size, which of course is not acceptable. If I do a resize, then immediately set it back, effectively doing two resizes, problem stays.
Miguel

---------------------------------------
Sent from my phone
Please excuse any boneheaded errors or random curses.

Miguel A. Castro
President & Principal Consultant
Melvicorp LLC

       



Microsoft Insider: ASP, VSX, C#, Azure

Twitter: @miguelcastro67

Also a Pluralsight author!

Check out my courses:
Building Multi-Client End-to-End Service Oriented Applications
Developing Extensible Software
Building Multi-Client End-to-End Service Oriented Application - Angular Edition 
WCF End-to-End
WCF Power Topics

**Comment by chaosmail** [comment]
hmm, that sounds really interesting. Would be great if you could make a Codepen with your settings do demonstrate the bug (you could start here: http://codepen.io/chaosmail/pen/ZQMjdN).

What also helps sometimes, is toggling a random option to redraw the chart, such as 

```
$scope.options.redraw = !$scope.options.redraw;
```

Best,
Christoph

**Comment by lorem--ipsum** [comment]
Any updates on this ?

**Comment by MangeshPimpalkar** [comment]
+1
