### ISSUE TITLE
Chart's X- Axis String Not Integer

### ISSUE THREAD

**Issue by jimgibbs** [n3-charts/line-chart#472]
I am attempting to use the n3-chart line chart. I have a data object that looks like:

{
      "time": "10:58:16 AM",
      "x": 0,
      "count": 16
}

I want to use the time property versus the x. Currently I cannot get this to work. I have created a codepen that should help illustrate what I am attempt to do.

http://codepen.io/jimgibbs/pen/dMvKZZ

Thanks!

**Comment by lorem--ipsum** [comment]
Hi, thanks for the interest ! Here's a CodePen where your dates are parsed using d3 to actual date objects. Hope this helps !

http://codepen.io/anon/pen/BKWPKB

**Comment by jimgibbs** [comment]
Thanks a bunch that does help!
