### ISSUE TITLE
"dot" not work in V2 with y2

### ISSUE THREAD

**Issue by samwzm** [n3-charts/line-chart#473]
it seems the line dot is not working in V2 when there are y and y2 axis. for example, even I specify type: ['line', 'dot'], there is no dot in the line. even worse, after I disable the series by clicking the label, and then enable it, all the dots will display in the line! I believe it's a bug. 

could anyone take a look?

thanks!

**Comment by samwzm** [comment]
update: 
1. the dot won't display at first (even specifying dot in type) -- which is not correct 
2. the dot won't display if not specifying dot in type, no matter disable/enable the series -- which is correct.

**Comment by lorem--ipsum** [comment]
Hey, thanks for the interest ! Can you provide an example of the bug, ideally on CodePen (you can find templates [here](http://n3-charts.github.io/line-chart/#/examples)) so we can investigate ? It'll be much easier for us, and much quicker for you :-)

We're closing this, but no hard feelings : it's just that we're trying to avoid zombie issues. Feel free to open a new one with a working example !
