### ISSUE TITLE
Top Line in graph always goes into upper margin

### ISSUE THREAD

**Issue by kandarpbhesaniya** [n3-charts/line-chart#474]
![image](https://cloud.githubusercontent.com/assets/11554884/13943749/46e49a7e-f025-11e5-9ca4-1df5422518ca.png)

how to fix it?

 mode = cardinal
tension = 0.7

**Comment by lorem--ipsum** [comment]
Use `margin: {top: 30}` or something ?

**Comment by kandarpbhesaniya** [comment]
not working..!!

**Comment by chaosmail** [comment]
Hi @kandarpbhesaniya 
Could you please provide a Codepen to reproduce this behavior, so we can better try to help you fixing this. This would help a lot! Maybe you could start with this pen http://codepen.io/chaosmail/pen/zrPJYb/
Best,
Christoph

**Comment by kandarpbhesaniya** [comment]
here is [codepen](http://codepen.io/anon/pen/RaNZXL) 
@chaosmail 

sorry to late response

**Comment by chaosmail** [comment]
Thanks for providing the example. I see that in v2 we are doing automatic clipping of the drawing area of the chart (in v1 we had an option to enable/disable this).Thats why on the top, the chart gets clipped. I would recommend setting the axis `max` option as a workaround until we fix this.

Here is a small example where I use an utility function to find the max value in the dataset for a specific key http://codepen.io/chaosmail/pen/KzqWgq
Theoretically you could do this also for multiple keys and take the max of them.

Hope that helps!

Best,
Christoph

**Comment by kandarpbhesaniya** [comment]
thanks @chaosmail
