### ISSUE TITLE
Add a `hideOverflow` option

### ISSUE THREAD

**Issue by chaosmail** [n3-charts/line-chart#476]
Currently, the clipping mask is always applied to the drawing area. However, it would be great to provide an option to disable this.

**Comment by hambyiii** [comment]
Is there a way to turn off the clipping mask without this option? I find that it is clipping the top couple of pixels of my chart. It's not much, but it is ugly.

**Comment by lorem--ipsum** [comment]
Guys, this is exactly why the `margin` option exists.

**Comment by hambyiii** [comment]
I tried playing with margin, but the clipping still occurs, which would say that the clipping is at fault no?

**Comment by lorem--ipsum** [comment]
Yeah, probably, however I can't see how. Could you provide a CodePen example that reproduces the bug ? That'd help a lot :-)

**Comment by chaosmail** [comment]
@lorem--ipsum clipping still occurs when margin is set

**Comment by chaosmail** [comment]
Duplicate of #474

**Comment by chaosmail** [comment]
In #474 you can find a link to a codepen

**Comment by lorem--ipsum** [comment]
Thanks ! I'll check it out !

**Comment by lorem--ipsum** [comment]
Okay so since `2.0.19`, there's an additional option on axes that will solve this specific use case. See it as an inner padding. You can see it in action [here](http://codepen.io/anon/pen/WwEBWK?editors=1010), but the meaningful part of it is :

```js
$scope.options = {
  axes: {
    x: {
      //...
    },
    y: {
      padding: {max: 5} // THIS
    }
  }
};
```

**Comment by chaosmail** [comment]
great, thanks a lot! this is amazing
