### ISSUE TITLE
Add optional color setting for axis

### ISSUE THREAD

**Issue by FyerPower** [n3-charts/line-chart#48]
Title says it all.  I added this feature to a local set of the code, however not really able to create a pull-request for it in its current state.  I am going to try and work some this weekend and create an official pull request.

Explanation: The background of my graphs are a non-white color and the black axis' are hard to read.  Adding a configurable color option that defaults to black would be a nice enhancement.

**Comment by hanifbbz** [comment]
+1. Would be great if the options object could have one more settings called `axisColor` that would set the color of the axis and its text. Currently we are doing it by CSS but it's more of a dirty hack. Our site has a dark theme and we can't use the default black color for axis.

**Comment by nishadotcom** [comment]
Yes, Obliviously
