### ISSUE TITLE
Chart is scaled up at eveyr form click

### ISSUE THREAD

**Issue by aligit** [n3-charts/line-chart#484]
Once the chart is generated based on a form, when I press on a text field or a button, the chart's height is increased. Any idea why this weird error might happen?

Thanks in advance

**Comment by lorem--ipsum** [comment]
Yeah, you should specify an explicit height for the chart's container.

**Comment by aligit** [comment]
Thanks man. That fixed the issue.

Best,
Ali

**Comment by lorem--ipsum** [comment]
![](http://www.reactiongifs.com/r/cheering_minions.gif)
