### ISSUE TITLE
Different dots

### ISSUE THREAD

**Issue by hambyiii** [n3-charts/line-chart#485]
Is it possible to draw entirely different dots, maybe even squares, or circles within circles (I work with a picky visual designer). In other words, is it possible to alter the dots beyond what is possible with CSS styling? This would also apply to the radius of the dots.

**Comment by lorem--ipsum** [comment]
Well, technically yeah, but that'd involve exposing the drawing routines through some properties... A bit of work, PR welcomes !

**Comment by hambyiii** [comment]
I would imagine that changing the dot radius would be easier, since that was possible in v1. Just passing in an option I would imagine.

**Comment by hambyiii** [comment]
So, I have thought about taking a look into this (before making a PR), but the documentation here: https://github.com/n3-charts/line-chart/wiki/Contribution seems out of date (no bower.json for example for the bower install step to work). If that is the only step that is wrong, then I will still take a look.
