### ISSUE TITLE
Bug when trying to set dataset to the result returned by promise

### ISSUE THREAD

**Issue by aligit** [n3-charts/line-chart#490]
I can successfully generate with predefined data. However when I try to dynamically add new dataset returned by the result of http.get the following error:

`angular.js:13236 TypeError: Cannot read property 'values' of undefined`.

this is my service:

```javascript
  getValveChartData(type, trim, size, diameter_unit){
     return this.http.get("http://localhost:5685/api/values/getValveChart?type="+type+"&size="+size+"&trim="+trim+"&diameter_unit="+diameter_unit).then(result => result.data );
  }

```
```javascript
In my controller:
    this.calculator.getValveChartData()
      .then(javab => {
        this.data = {
          dataset2: result
        };
};

```

If I replace result with some valid array it will generate the chart but I don't know why the result will launch that error.

Thanks

**Comment by chaosmail** [comment]
Hi @aligit 
can you check the `result` object if it actually contains something? Maybe you could even add an if-statement to only set `dataset2` if result exists. 
```
this.calculator.getValveChartData()
      .then(javab => {
        console.log(result);
        this.data = {
          dataset2: result
        };
```

Can you show your other options as well? Maybe you defined `dataset2` already before it is loaded.

Best,
Christoph

**Comment by aligit** [comment]
Hi @chaosmail 
Thanks for your reply. the result is an array of object:
{x_cv:100,y_opening:100.46}.
I only defined dataset2 in "options" like so:
    this.options = {
      series: [
        {
          axis: "y",
          dataset: "dataset0",
          key: "y_opening",
          label: 'Actual curve',
          color: "#1f77b4",
          type: ['line', 'dot'],
          id: 'mySeries0'
        },
        {
          axis: "y",
          dataset: "dataset1",
          key: "y_opening",
          label: 'Activity range',
          color: "hsla(88, 48%, 48%, 1)",
          type: ['line', 'dot','area'],
          id: 'mySeries1'
        },
        {
          axis: "y",
          dataset: "dataset2",
          key: "y_opening",
          label: 'curve',
          color: "hsla(88, 48%, 48%, 1)",
          type: ['line', 'dot','area'],
          id: 'mySeries2'
        }
      ],
      axes: {x: {key: "x_cv"}}
    };
That's very weird

**Comment by chaosmail** [comment]
You are already defining `dataset2` in the option, when the dataset is (most likely) not available (in the beginning). When you define your dataset, just init `dataset3`:
```
this.data = {
    ...
    'dataset3': []
}
```

Let me know if this helps

**Comment by aligit** [comment]
Thanks @chaosmail  didn't help. Still getting the same error

**Comment by chaosmail** [comment]
could you share also the part where you define the dataset and the HTML snippet where you bind it?

**Comment by aligit** [comment]
Yes sure
```javascript
    <div class="row">
        <div class="col-md-6 chart">
            <h1>Opening Curve</h1>
            <linechart data="vm.data" options="vm.options"></linechart>
        </div>
    </div>
```

### First definition in the constructor:
```javascript
    this.data = { 'dataset0': [], 'dataset1': [], 'dataset2': []};

    this.default_series = [ this.chartoption.series(0, ['line', 'dot'],"#0067B2", 'Actual curve'),
        this.chartoption.series(1, ['line', 'dot','area'],"#0067B2", 'Activity range')
    ];
    this.series = this.default_series;
    this.default_axes = {x: {key: "x_cv"}};
    this.options = {
      series: this.series,
      axes: this.default_axes
    };
```

Then the first time the data is generated(which works fine too)
```javascript
    this.calculator.getResults(...)
      .then(result => {
        this.datasets = [];
        this.datasets.push(result.chart_dataset_actual_curve);
        this.datasets.push(result.chart_dataset_activity_range);
        this.data = {
          'dataset0': this.datasets[0],
          'dataset1': this.datasets[1]
        };
    });
```
And here is the last part where I try to add new dataset:
```javascript
    this.calculator.getValveChartData()
      .then(javab => {
        debugger;
        this.data = {
          dataset2: javab
        };
        const index = this.series.length;
        const datasetname = "dataset"+index;
        this.options.series.push(this.chartoption.series(index, ['line', 'dot'],"", 'curve'));
    });
  }
```
Thanks

**Comment by aligit** [comment]
Dear @chaosmail ,
The problem was due to a wrong series objects and setting data before the options.

The problem was solved. Thanks so much for your help

**Comment by chaosmail** [comment]
Great, I am glad it is working for you!
