### ISSUE TITLE
Is log scale supported ?

### ISSUE THREAD

**Issue by HadrienPierart** [n3-charts/line-chart#492]
Before asking anything, please know that this lib has been central to serveral of my projects to create dashboard and internal reporting, which is awesome ! Thx !

I can see in d3 source that you can do a log scale for wide ranges of data. How do we do that with your lib ? Is it possible with v1 ? v2 ?

Thanks a lot !

**Comment by chaosmail** [comment]
Hi @HadrienPierart 

In v1 this feature is supported via the `type='log'` setting in the axis options. I don't think we have already ported this to v2. However, this should be a quite easy feature to add if you are keen to submit a PR ;)

Best,
Christoph

**Comment by HadrienPierart** [comment]
:D
I'd glad to submit a PR, but I havent ported any of my graph to v2, so Im a bit behind on schedule :(

That said, I get weird results on my graph. Maybe I need to dig in a bit deeper on the domain/range settings...
Thx for the quick answer !

**Comment by chaosmail** [comment]
hmm, mabye you are taking `log` of 0s somewhere (which is very bad), this happened to me when i used log scales.

**Comment by HadrienPierart** [comment]
Here is what I get. I have values ranging from 0 to 150 000 on Y.
I'd like to skip a ton of the ticks on the Y axis because its totally unreadable right now...
![screenshot from 2016-04-14 11 27 22](https://cloud.githubusercontent.com/assets/738871/14523412/e5d59bae-0233-11e6-800d-ab9556527942.png)

**Comment by chaosmail** [comment]
if your values span so many magnitudes, you better take an exponential or scientific tick format

**Comment by chaosmail** [comment]
you can use d3 formats directly in v1 and as a formatting function in v2 https://github.com/mbostock/d3/wiki/Formatting

**Comment by HadrienPierart** [comment]
oh ! I didnt know about these indeed. They are not directly supported through a type in v1 ?

**Comment by chaosmail** [comment]
they are, you can just plug the d3 formatter string into `ticksFormat` setting in the axis option and it will just work ;)

**Comment by chaosmail** [comment]
`ticksFormat:'s'` for example is quite cool.
But you may need to increase the margin on the left side a little, to make it more readable. you can do this with the `margin: {left: 80}` option

**Comment by HadrienPierart** [comment]
ok, yeah indeed, it changes the scale tick format to something like 2e4 but there still is like 40 ticks on the axis. 4 or 5 would be enough but the option `ticks: 5` does not have any effect

**Comment by chaosmail** [comment]
yeah, the ticks option goes directly into d3, and it is quite broken. another possibility is to set the tick values (maybe based on some `max` value using d3.range and d3.scale) directly.

**Comment by HadrienPierart** [comment]
Ok, I finally got it to work. It didnt like having a 0 amongst the ticks values for some reason :
My Y configuration :
`y: { type: 'log', ticks: [1, roundTo10Pow(data.yMax/1000), roundTo10Pow(data.yMax/100), roundTo10Pow(data.yMax/10), roundTo10Pow(data.yMax)], labelFunction: lab => lab }`

![screenshot from 2016-04-14 12 11 02](https://cloud.githubusercontent.com/assets/738871/14524736/145caba6-023a-11e6-8c7c-ce20aa8e9e3c.png)

Thanks a lot for the help !

**Comment by chaosmail** [comment]
yeah, that's what i meant. log(0) is not defined ;)

**Comment by chaosmail** [comment]
great looks nice, maybe you can try exponential ticks format, like 2e6 or sth

**Comment by HadrienPierart** [comment]
Yeah, I tried the exp ticks format but really not that pretty, so I stuck to numbers.
Indeed, log(0) is not defined. Math classes are so far away that you tend to forget the simple things...

**Comment by chaosmail** [comment]
:D don't worry, happened also to me when i was using log scales

**Comment by lorem--ipsum** [comment]
There's an option to use log axes in v2 a well, see [this codepen](http://codepen.io/anon/pen/KzoxmG) spawned from the examples page. Also, `log(0)` is `undefined` because

![](http://www.rapidtables.com/math/algebra/logarithm/lim_log_0.gif)
