### ISSUE TITLE
Chart won't scale with data

### ISSUE THREAD

**Issue by m3Lith** [n3-charts/line-chart#498]
### Summary
I'm having a hard time figuring out why the chart won't scale with the my data. It looks as if it takes the last point and uses its value as a max-y, min-y value is also wrong.

### Expected behavior
Chart would scale to fit all data points.

### Actual behavior
Chart doesn't scale as expected.

### CodePen example
http://codepen.io/anon/pen/JXwMmO

### Steps to reproduce
Just look at it.

**Comment by chaosmail** [comment]
Hi @m3Lith 
the values you provide to the chart are all strings; if you convert them to numbers it will work fine.
Best,
Christoph

**Comment by m3Lith** [comment]
Heh, indeed. I'm actually using .toFixed() when forming values and forgot it returns a string... Thanks!
