### ISSUE TITLE
Updating line

### ISSUE THREAD

**Issue by scarletpedroza** [n3-charts/line-chart#503]
Hi all, first I must say that I am new in AngularJS and I am implementing the Linechart in my real-time application, but I have a problem with updating the graph. Every 5 seconds must update the data but as it is updated is going down occupying the entire browser. I tried with $scope.$apply but it does not work.

so it looks at first
![graph](https://cloud.githubusercontent.com/assets/17975786/15398978/9f500100-1daf-11e6-801c-f9127263832b.png)

but after
![graph2](https://cloud.githubusercontent.com/assets/17975786/15398995/aece63c4-1daf-11e6-8404-ebf2461e5ae9.png)

I need help, thnks :)

**Comment by wasper1** [comment]
Have You tried to force height with wrapper ? 

```
.chart-container, .chart {
  width:800px;
  height:330px;
}
```

```
<div class="chartbox-wrapper">
    <linechart class="chartbox" data="data" options="options"></linechart>
</div>
```

**Comment by lorem--ipsum** [comment]
@scarletpedroza any updates on this ?
