### ISSUE TITLE
Changes in dataset are acknowledged, but the dots are not redrawn

### ISSUE THREAD

**Issue by ericleb010** [n3-charts/line-chart#506]
Plunker: https://plnkr.co/edit/Ol5zTBPDlzS8im8ScfGj?p=preview

I'm using a dataset for each graph on my page, and updating that dataset when there is a change in the data. When the user changes the dataset, the graph responds by redrawing as expected.

However, if I have dot type selected, I've noticed that dots are never generated past the graph's initialization. So any time I change my dataset to one with more data points, the graph will sometimes reuses dots, but never generates new ones as needed. 

The plunker above illustrates this. Hopefully there's a simple fix here?

**Comment by lorem--ipsum** [comment]
Hey, thanks for the detailed report. I'll take a look, it's probably the framework's fault at first glance.

**Comment by lorem--ipsum** [comment]
Hey, could you check out the branch named dots_update, build it (`./kickstart.sh && gulp build:angularjs`) and try ? It should be fixed.

**Comment by ericleb010** [comment]
That works! Thanks.

**Comment by lorem--ipsum** [comment]
Okay, released 2.0.27.
