### ISSUE TITLE
EventManager preventing normal functionality of mouse events in window

### ISSUE THREAD

**Issue by ericleb010** [n3-charts/line-chart#509]
Codepen: http://codepen.io/anon/pen/RRWWPb

I noticed that when your code is inserted into a page, some HTML controls that rely on proper functionality of the mouseup / move events no longer work when the event is fired from outside the SVG object.

To reproduce: click the slider in any way below the graph. You'll notice that you can get one click out of it before both the slider and the graph will no longer react to the mouse.

I think the key to the solution is in lines 60 and 64 in src/utils/EventManager.ts, because when I commented those lines out, things seemed to function normally again. I don't know if there are side effects though.

**Comment by epistemancer** [comment]
+1 , we're having a similar problem and removing the `preventDefault`s solved it.  I'd PR the change but I don't fully understand why the `preventDefault`s are there or what the ramifications of removing them are, but FWIW removing them doesn't seem to have any detrimental effects to the behavior of the line-chart.

**Comment by lorem--ipsum** [comment]
I'll take a look at this tomorrow or on Sunday. I think that this `preventDefault` thing might have been added in order to prevent several charts to interact with each other...

**Comment by epistemancer** [comment]
sweet, thanks!
