### ISSUE TITLE
Make it more obvious n3-charts/line-chart doesn't work with D3 v4.*

### ISSUE THREAD

**Issue by arfordweb** [n3-charts/line-chart#516]
Ouch.  I just spent way too long trying to figure out why I was getting the error:

angular.min.js:108 TypeError: Cannot read property 'apply' of undefined
    at EventManager.trigger 
At LineChart.js:718:38

Turns out I was using D3 version 4 rather than the latest version 3, per this Issue from a month ago: https://github.com/n3-charts/line-chart/issues/513

Could you guys update the documentation and README to make it more apparent that this plugin isn't compatible with version 4 of D3 yet?  I'm sure it will save future adopters of your plugin a great deal of heartache.

Thanks.

**Comment by lorem--ipsum** [comment]
Good idea ! Thanks :)

**Comment by stowball** [comment]
I just wasted 30 minutes on this, too.

Any plans for v4 support?

**Comment by sitawit** [comment]
I think the preferable solution is to change package.json to be more specific. For example, using D3: 3.5.17  (latest of 3.x) instead of ^3.5.5.

**Comment by arfordweb** [comment]
@sitawit It is.  My suggestion is to make it more obvious in the docs that you'll have to do this rather than attempting to use v4.  That would be a short-term solution anyways.

**Comment by arfordweb** [comment]
And it looks like that was done.  It's now at the top of the doc.  Thanks!
