### ISSUE TITLE
Points on same x value don't get dots

### ISSUE THREAD

**Issue by raxion** [n3-charts/line-chart#518]
Hi,

I wonder if this is a bug. When I have 2 points on the same x value, only one gets a dot.
You can see it here.
http://codepen.io/raxion/pen/NAQJYb?editors=0010

I have 3 data points where x equals 3 but only the first one gets a dot. I would like that all of them to have a dot.

**Comment by chaosmail** [comment]
Hi @raxion 
we currently use the x value as index for each data point, and hence only draw one point per x value. As in your case there are many examples whey this is not good and we should fix this. PR welcome ;)
Best, Christoph

**Comment by raxion** [comment]
I understand, and I have looked through the code but I'm not sure where to start :)
