### ISSUE TITLE
Error: this._dispatch[event] is undefined

### ISSUE THREAD

**Issue by skirscher** [n3-charts/line-chart#529]
Stack trace (minus primary url for security purposes):

EventManager.prototype.trigger@/LineChart.js:718:17
LineChart/this.link/updateAll@/LineChart.js:3137:25
$RootScopeProvider/this.$get</Scope.prototype.$digest@/angular-1.5.6/angular.js:17220:23
$RootScopeProvider/this.$get</Scope.prototype.$apply@/angular-1.5.6/angular.js:17486:13
done@/angular-1.5.6/angular.js:11637:36
completeRequest@/angular-1.5.6/angular.js:11843:7
requestLoaded@/angular-1.5.6/angular.js:11776:9

I do not know if this is related to d3.js v4 or not at this point. Trying to get the provided sample code working within a project which I plan to add charts into. Currently nothing related to the line-chart library is functional/displaying and up until recently I was getting errors upon moving my mouse cursor around the page, 1 error with each pixel that the mouse moved.

I can provide better information via email at: stephenkirscher@gmail.com; please contact me for such information.

**Comment by chaosmail** [comment]
Please use D3.js Version 3, looks like an error from the D3 API

**Comment by skirscher** [comment]
Thanks for the response. I'll see if I can find it on Monday and let you
know if I have any further issues

**Comment by skirscher** [comment]
Updated my d3js to version 3 instead of 4 per recommendation received via email. This resolved the issue.
