### ISSUE TITLE
Dot Chart Issues

### ISSUE THREAD

**Issue by skirscher** [n3-charts/line-chart#532]
I wanted to display a scatter plot using the "dot" chart with zoom enabled. However, using the latest version of n3-charts, I was unable to get the zoom feature to work properly. I reverted back to an earlier version of n3-charts (v1.11) and was able to get the zoom feature functional but now there is a line being rendered between each of the dots which I cannot figure out how to remove. It's making my scatter plot look like a very interesting starburst. What confuses me even further is that the current version of n3-charts doesn't do this. Any help that can be provided with either resolving the lines issue or getting the most current version of n3-charts to work with the zoomable feature would be greatly appreciated.

Note: I am getting a sample set of data from an Oracle database every time I load/reload the page as my data set for the chart. This being said, here is the `$scope.options` part of my code from my controller:

`$scope.options = {
	margin: {
	  bottom: 80,
	  right: 80
	},
	pan: {
		x: true,
		x2: false,
		y: true,
		y2: false
	},
	series: [{
		y: "y",
		dataset: "numerical",
		key: "x",
		label: "Test",
		color: "hsla(88, 48%, 48%, 1)",
		type: ["dot"],
		id: "mySeries0"
	}],
	axes: {
		x: {
			key: 'x', zoomable: true
		}
	},
	hideOverflow: true,
	zoom: {
		x: true,
		y: true
	}
};`

**Comment by lorem--ipsum** [comment]
Hi ! What do you mean by "work properly" ?

**Comment by skirscher** [comment]
The zoom was not working...at all.

**Comment by skirscher** [comment]
It also isn't working in one of the codepen examples I found through this GitHub:
http://codepen.io/anon/pen/JXWavo

**Comment by lorem--ipsum** [comment]
This is something we should totally communicate more about : zooming works by pressing alt and clicking. Simple click and drag is dedicated to panning. Let me know if that helps :)

**Comment by skirscher** [comment]
That does help. Definitely needs to be documented better, I had been double clicking all this time... 0_o

**Comment by skirscher** [comment]
Okay so when I stated it helped, I was only looking at the codepen project. When I went to replace the older versions of n3-chart's library files on my server with the newest/latest version (still keeping d3.js version 3.5); it broke my chart. Now it is giving me a the following error:

TypeError: this.sets[t.dataset] is undefined
e</e.prototype.getDatasetValues()   line-chart.min.js:1
n</i.prototype.updateData()    line-chart.min.js:2
i</e.prototype.updateSeries/<()    line-chart.min.js:2
Co.each/<()   d3.v3.min.js:3
Y()   d3.v3.min.js:1
Co.each()   d3.v3.min.js:3
i</e.prototype.updateSeries()   line-chart.min.js:2
i</e.prototype.updateSeriesContainer()   line-chart.min.js:2
i</e.prototype.softUpdate()   line-chart.min.js:2
bound ()   self-hosted
t()    d3.v3.min.js:1
e</t.prototype.trigger()    line-chart.min.js:1
e/this.link/d<()     line-chart.min.js:2
e</t.debounce/</n<()     line-chart.min.js:1

Any suggestions?

**Comment by lorem--ipsum** [comment]
Hm. Any chance you could post a CodePen that replicates the issue ? That'd help tremendously

**Comment by skirscher** [comment]
I will see what I can do...

**Comment by skirscher** [comment]
I was able to get a plunkr together recreating the errors. Hope this helps:
http://plnkr.co/edit/TR5mmmI0hQpSL0dkwGcX?p=preview

**Comment by lorem--ipsum** [comment]
Okay [here's a working version](http://plnkr.co/edit/V9okNtzZU0bVeLKYKeE5?p=preview).

You forgot a couple of things :
 1. the options were missing some stuff (the options structure changed from v1 to v2, I think you had v1 options especially regarding the series `key`)
1. the data structure wasn't right (again, probably v1 data — we now use an object that contains datasets)
1. the LineChart's CSS file wasn't linked
1. the data wasn't sorted on the abscissas and contained an extreme point (see the comment in the code)

Hope that helps. You might wanna give a height and a width to your chart, otherwise it'll get its dimensions wrong (useful for tooltip positioning as well I think). Also, LineChart's default style is more suitable for display on a light background, so you might wanna change that as well (but that's more of a personal opinion ^^).

**Comment by skirscher** [comment]
Any suggestions?

**Comment by skirscher** [comment]
Thanks for your help. I was able to get things working by switching up the options and fixing how I was creating my data. The color scheme is actually something that was decided upon by the project lead so don't think that will be changed. However, I will most likely be setting the height/width of chart. In doing so, would this affect the scale? Also, the higher numbers are going to end up in our data because it's related to job file count averages among other stats we are reporting upon. I will bring up considering the removal of really high counts that wouldn't correlate to the rest of the data and just be a random spike, thanks for your input.

**Comment by skirscher** [comment]
One other question, any way to adjust the scale? Would like to be able to keep it smaller so that it shows the correlation better, even when there are the huge spikes.

**Comment by lorem--ipsum** [comment]
Yeah, you can use min and max on the axes in the options to customize the chart.
Take a look at [the documentation](http://n3-charts.github.io/line-chart/#/docs) for moar.

**Comment by skirscher** [comment]
K, thanks! ^_^
