### ISSUE TITLE
Is there a way to hide the legend?

### ISSUE THREAD

**Issue by johannds** [n3-charts/line-chart#534]
If there is, I can't find it in the code, nor in the docs. Any ideas?

**Comment by chaosmail** [comment]
Hi @johannds 
you can do a lot of awesome styling directly with CSS. You can hide the legend via
```
.chart-legend {
  display: none;
}
```

Here is a quick demo http://codepen.io/chaosmail/pen/bBaXyN

Best,
Christoph

**Comment by sqnkov** [comment]
There appears to be a ```drawLegend: boolean``` option but it does not work for me.

**Comment by TempestSpectre** [comment]
@sqnkov http://codepen.io/chaosmail/pen/bBaXyN

**Comment by johannds** [comment]
Sweet, thanks.

**Comment by sqnkov** [comment]
@TempestSpectre  , CSS works, but I was hoping for a built-in method. But hey.. CSS wroks.
