### ISSUE TITLE
[Question]If I want to update the chart data, based on the timeline, what should I do?

### ISSUE THREAD

**Issue by wu-sheng** [n3-charts/line-chart#539]
Hi, I want to use **line-chart** as a part of [sky-walking APM](https://github.com/wu-sheng/sky-walking) UI. As an application performance management, we always should charts based on time line, it is some charts like http://n3-charts.github.io/line-chart/#/examples#time_series. But these did not show how to do when data updated, as time changed.

Let's say if we get data at first time, the data is between 14:00 - 15:00; and the second time, the data is between 14:02-15:02. We want to update the chart, but do not want to refresh the page.

I think you definitely support this feather, but I did not find the examples and docs, yet. Can you guys give me some guides?

**Comment by chaosmail** [comment]
Hi @wu-sheng 
line-chart is supporting this, just update `$scope.data`, bind it to n3-charts (see the examples) and everything in there will be automatically updated in the chart.
Hope that helps!
Best,
Christoph
